### ISSUE TITLE
Wayvnc issue to start

### ISSUE THREAD

**Issue by Fitap** [any1/wayvnc#100]
Hi, I run on Gentoo with KDE5 + Wayland + SDDM and when I do start wayvnc get this error:

`wl_registry@2: error 0: invalid version for global wl_seat (10): have 5, wanted 7
ERROR: Virtual Pointer protocol not supported by compositor.
ERROR: Failed to initialise wayland
`
Any idea?
Regards

**Comment by danshick** [comment]
> Hi, I run on Gentoo with KDE5 + Wayland + SDDM and when I do start wayvnc get this error:
> 
> `wl_registry@2: error 0: invalid version for global wl_seat (10): have 5, wanted 7
> ERROR: Virtual Pointer protocol not supported by compositor.
> ERROR: Failed to initialise wayland
> `
> Any idea?
> Regards

I don't think KDE supports the necessary wayland protocols to make use of wayvnc. wayvnc specifically targets wlroots-based compositors like sway, wayfire, and river.

**Comment by Fitap** [comment]
Thanks for reply.
