### ISSUE TITLE
RealVNC doesn't work with authentication on

### ISSUE THREAD

**Issue by jso8910** [any1/wayvnc#101]
I found an issue with WayVNC and RealVNC (as a viewer). I am trying to use vnc to connect with my linux laptop from MacOS. I tried tigervnc but there were scrollbars which I couldn't fix (scaling wasn't right) and then I tried realvnc. It works... but only if I set `enable_auth` to false. Any possible fixes to this? I don't want to have my laptop open to the world without a password.

**Comment by any1** [comment]
Neat VNC and RealVNC just don't support the same authentication protocol extensions. RealVNC's extension has not been shared with the public, so we cannot implement it without going through the trouble of reverse engineering it. Open extensions that are supported by RealVNC are easily defeated and should not be implemented in Neat VNC as they would provide a false sense of security.

I recommend ssh tunnelling.
