### ISSUE TITLE
invalid version for global wl_seat

### ISSUE THREAD

**Issue by gerstrong** [any1/wayvnc#104]
When I try to run this on a Manjaro Gnome system I get the following error and the app just shuts down:

    wl_registry@2: error 0: invalid version for global wl_seat (18): have 5, wanted 7
    ERROR: Virtual Pointer protocol not supported by compositor.
    ERROR: Failed to initialise wayland

Using kernel 5.10.42-1-MANJARO, Wayland 1.19.0-1. I built the app myself, based on the master branch, commit 3b6a07a3b6fe1e6ce3d5505fed09263bb6557019

**Comment by any1** [comment]
Your wayland compositor (Gnome) does not support the required protocols. Wayvnc works for wlroots based compositors such as sway, hikari and wayfire.
