### ISSUE TITLE
ERROR: Failed to initialize renderer, upon starting wayvnc

### ISSUE THREAD

**Issue by codebam** [any1/wayvnc#11]
strace of the crash: https://0x0.st/izms.txt

**Comment by danshick** [comment]
This is the commit that introduced the bug 4b3be2c

**Comment by any1** [comment]
Uhm, this issue predates the regression which I introduced yesterday. @codebam are you still experiencing this problem?

**Comment by danshick** [comment]
Good catch. This was the culprit for me. I suppose this error message could have many causes.

**Comment by codebam** [comment]
I updated to master and rebuilt. Now I'm getting this error when I try to run wayvnc.

```
DEBUG: EGL: eglGetPlatformDisplayEXT: _eglGetPlatformDisplayCommon
ERROR: Failed to initialise renderer
```

Strace: https://0x0.st/iH-Z.txt

I can open this as a separate issue if you would like?

**Comment by any1** [comment]
> I can open this as a separate issue if you would like?

No it's most likely the same issue. What distro are you running?

**Comment by codebam** [comment]
Oh okay cool.

This is on Alpine Linux (edge). I built and symlinked wayvnc to my $PATH to run it. I also tried ./wayvnc from within the build directory.

**Comment by danshick** [comment]
When I hear Alpine, I immediately think glibc compatibility issues. Could this be musl related?

**Comment by any1** [comment]
Well, I could try compiling with musl on my arch linux system and see what that does.

**Comment by any1** [comment]
The issue is that Alpine Linux does not compile mesa with off-screen rendering. The platforms in the config step should include "surfaceless". See https://git.alpinelinux.org/aports/tree/main/mesa/APKBUILD#n129.
