### ISSUE TITLE
Vertical output dimensions cause artifacts and crashing

### ISSUE THREAD

**Issue by nindwen** [any1/wayvnc#110]
We discussed this on IRC a bit, I tried to collect everything I know here. Hopefully this helps!

- Sway 1.5.1 / Ubuntu 21.04
- This affects wayvnc 87c040c built with any1/neatvnc@dad1948 (latest masters at the moment). v0.4.0 seems unaffected.

### Steps to reproduce

Create a headless output and set resolution:

```sh
$ swaymsg create_output
$ swaymsg output HEADLESS-1 resolution 1404x1872  
```

Start wayvnc:

```bash
$ ./build/wayvnc --output=HEADLESS-1 192.168.x.x  5900
```
Now I can connect to it with my VNC client. But there are artifacts, mostly in the bottom part of the image. For example:

<img src="https://user-images.githubusercontent.com/52139145/132717963-c8069770-cefd-4b42-91ec-ab3f017fa8fb.jpg" width=200>

After a while, usually when doing some action, wayvnc process segfaults.

```gdb
(gdb) bt
#0  0x00007f5af29d6820 in ?? () from /lib/x86_64-linux-gnu/libpixman-1.so.0
#1  0x00007f5af296d21d in pixman_image_composite32 () from /lib/x86_64-linux-gnu/libpixman-1.so.0
#2  0x0000557c55f838ae in ?? ()
#3  0x0000000000000000 in ?? ()
```

If I do the exact same process, but with resolution 1872x1404 (instead of 1404x1872), everything seems to work fine. If the resolution is 1872x1404, but I rotate it with:

```
$ swaymsg output HEADLESS-1 transform 90
```

...The problems are back again. 

I also tried with 1080x1920 and it behaved similarly as 1404x1872, so it doesn't seem to be about the exact resolution.

**Comment by any1** [comment]
Fixed here: https://github.com/any1/neatvnc/commit/a14b829743f3276a736fc1958c12f64d2e52f936
