### ISSUE TITLE
WayVNC display in mirror

### ISSUE THREAD

**Issue by pagnchanak** [any1/wayvnc#111]
Based on older commit, wayvnc works fine on droidian (debian bullseye), except some artifacts during VNC..
However, on latest commit, the artifacts are gone and display is smoother, but it isshowing in mirror. See screenshot for both.

**OLD:**
wayvnc: v0.4.0-6-g87c040c (master)
neatvnc: v0.4.0-21-gdad1948 (master)
aml: v0.2.0-1-ga1baa97 (master)

![OLD](https://user-images.githubusercontent.com/68956560/134218939-18e1c4ee-e4a1-4672-8813-79079116e760.png)

**NEW:**
wayvnc: v0.4.0-8-g0d05b08 (master)
neatvnc: v0.4.0-34-g783ac9d (master)
aml: v0.2.0-1-ga1baa97 (master)

![NEW](https://user-images.githubusercontent.com/68956560/134218950-0ab9926e-044e-432a-ab50-afa2e7db884e.png)

**Comment by any1** [comment]
Yeah, I guess I forgot to carry over the the y-inversion code. Newest wlroots doesn't send y-inverted frames, so it didn't come up when testing.

**Comment by any1** [comment]
Should be fixed now

**Comment by pagnchanak** [comment]
Thanks. Confirm it is fixed now with the latest build.
