### ISSUE TITLE
multiple outputs?

### ISSUE THREAD

**Issue by rpodgorny** [any1/wayvnc#112]
hi, is there a way to provide multiple outputs? if not, what should be done to add such feature? thanks!

**Comment by lack** [comment]
If/when you do this, can you make it optional please? I actually like the fact that wayvnc only shows one of my displays (fits better in my client!)

**Comment by lack** [comment]
As discussed elsewhere, we have so far identified 4 different use-cases around what to do when VNC connects to a remote system with multiple displays:
- Show all the displays as one giant screen (this is what x11vnc does)
- Show only one display in the VNC client, but have a mechanism (keybind maybe?) to switch to other displays
- Show only one display in the VNC client, and temporarily disable all other displays (so all windows & desktops move to this display), and undo on disconnect (I like this for sway)
- Create a new display as a side-car and extend the existing displays with it (effectively use a vnc client as an additional monitor!)

**Comment by lack** [comment]
I have completed a series of PRs that implement part of this.

#171 introduces the `wayvncctl` command line tool, which can send IPC messages to a running wayvnc instance.  And one of the commands I implemented is `set-output` which allows runtime switching of the Wayland output device.

So now you can set up a keybinding in your environment to run:

```
wayvncctl set-output --cycle=next
```

which will cycle through all your multiple outputs on-the-fly.

**Comment by lack** [comment]
Just finishing up #200 which adds an example script to disable all outputs but one when a client connects, and re-enable them on disconnect.

**Comment by lack** [comment]
In light of the current state of support, I'm closing this issue and opening a new one for each of the outstanding use cases.

**Comment by lack** [comment]
Closing this because multiple outputs are now pretty nicely supported.

@rpodgorny : If the work done so far doesn't meet your needs, please comment on the new related issues (#225 or #226), or open a new issue with more info about what behaviors you'd like to see with wayvnc and multiple outputs.
