### ISSUE TITLE
can't connect to wayvnc when dpms off

### ISSUE THREAD

**Issue by langyxxl** [any1/wayvnc#114]
My laptop sway's idle configuration:
 exec swayidle -w \
          timeout 300 'swaylock -f -c 000000' \
          timeout 600 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
          before-sleep 'swaylock -f -c 000000'

1. wait 600s or run swaymsg "output * dpms off"' from ssh
2. start wayvnc
3. use another pc vnc-client to connect to laptop's wayvnc

vnc-client can't connect to wayvnc.

**Comment by lack** [comment]
Workaround: If you have swayidle set up to set "DPMS on" on resume, when I connect to an idle system my vnc client connects successfully and shows a weird-looling grey screen, but it soon wakes up and shows my swaylock screen.

I agree that manually setting "DPMS off" with a client connected to wayvnc acts in an unexpected way: the client display freezes (not even the wayvnc-rendered mouse cursor updates) even though inputs are still sent through to sway.

I'd actually vote that wayvnc should continue to send window updates to the client even if DPMS has blanked the screen... But if that's not possible a black screen might be better than a frozen one.
