### ISSUE TITLE
Cannot connect to ligthdm auto login session

### ISSUE THREAD

**Issue by feklee** [any1/wayvnc#117]
So I'm trying to run Sway on a headless Raspberry Pi 4 / Ubuntu 21.10 and connect to it via VNC.

Remote connection via VNC works fine when I start Sway in headless mode:

    $ WLR_RENDERER_ALLOW_SOFTWARE=1 WLR_BACKENDS=headless WLR_LIBINPUT_NO_DEVICES=1 dbus-run-session sway
    $ ./build/wayvnc

However, I would like to utilize the Raspberry Pi's graphics adapter, even though no screen is attached. So I set up Sway to start automatically from lightdm. This works. Sway is running as the regular user that I use for testing. There is no error message when I run:

    $ ./build/wayvnc

So far, all looks good, but I just cannot connect with a VNC client. In fact I cannot even telnet into `localhost 5900`.

What I also tried, but again without any output:

    $ meson debug
    $ ninja -C debug
    $ ./debug/wayvnc

*How do I find out more?*

**Comment by yobert** [comment]
Could you paste the output of this, run from another terminal while wayvnc is running:

    sudo netstat -natpuo | grep wayvnc

**Comment by feklee** [comment]
Thank you for the suggestion. Unfortunately, I already shut down the server. I may try again in the future.

**Comment by lack** [comment]
Closing this issue. Please reopen if it's still happening!
