### ISSUE TITLE
wayvnc fails on Virtual Pointer Protocol

### ISSUE THREAD

**Issue by dirjud** [any1/wayvnc#120]
On Fedora 35 running gnome, I get this error when I run wayvnc:

```
wl_registry@2: error 0: invalid version for global wl_output (4): have 2, wanted 3
ERROR: Virtual Pointer protocol not supported by compositor.
ERROR: Failed to initialise wayland
```

Here is the version output:
wayvnc -V
wayvnc: 0.4.1
neatvnc: 0.4.0
aml: 0.2.0

**Comment by any1** [comment]
Please see the first sentence in the first paragraph in the README.
