### ISSUE TITLE
Segfault upon pressing key when /usr/share/X11/xkb is missing

### ISSUE THREAD

**Issue by commander-derp** [any1/wayvnc#122]
So I'm experimenting with using wayvnc (current version in my package manager is 0.4.0) to control my phone (Librem 5, runs Linux, has Gentoo chroot) via desktop. It has a fairly minimal set of packages installed in the chroot so maybe missing stuff you'd expect on a normal desktop. I installed and ran the program, noting that it spat out an error message: "xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb". After this, however, it did connect, I could see the screen and move and click the mouse. I figured that that error message just meant that it was missing some keymaps and fall back to some defualt or something and may not handle all the keys correctly. Upon pressing any key however, it immediately segfaults with the following backtrace:

```
Thread 1 "wayvnc" received signal SIGSEGV, Segmentation fault.
0x0000fffff7e1c8cc in xkb_state_update_key (state=0x0, kc=43, direction=XKB_KEY_DOWN) at ../libxkbcommon-1.3.1/src/state.c:748
748	    const struct xkb_key *key = XkbKey(state->keymap, kc);
(gdb) bt
#0  0x0000fffff7e1c8cc in xkb_state_update_key (state=0x0, kc=43, direction=XKB_KEY_DOWN) at ../libxkbcommon-1.3.1/src/state.c:748
#1  0x0000aaaaaaaaa5d4 in keyboard_apply_mods (self=0xfffffffff0b0, code=43, is_pressed=true) at ../wayvnc-0.4.0/src/keyboard.c:275
#2  0x0000aaaaaaaaab84 in keyboard_feed_code (self=0xfffffffff0b0, code=43, is_pressed=true) at ../wayvnc-0.4.0/src/keyboard.c:435
#3  0x0000aaaaaaaa6154 in on_key_code_event (client=0xaaaaaaaea6c0, code=35, is_pressed=true) at ../wayvnc-0.4.0/src/main.c:468
#4  0x0000fffff7e57fcc in on_client_qemu_key_event (client=0xaaaaaaaea6c0) at ../neatvnc-0.4.0/src/server.c:661
#5  0x0000fffff7e58038 in on_client_qemu_event (client=0xaaaaaaaea6c0) at ../neatvnc-0.4.0/src/server.c:676
#6  0x0000fffff7e58630 in on_client_message (client=0xaaaaaaaea6c0) at ../neatvnc-0.4.0/src/server.c:839
#7  0x0000fffff7e58748 in try_read_client_message (client=0xaaaaaaaea6c0) at ../neatvnc-0.4.0/src/server.c:869
#8  0x0000fffff7e5884c in on_client_event (stream=0xaaaaaaaea5f0, event=STREAM_EVENT_READ) at ../neatvnc-0.4.0/src/server.c:917
#9  0x0000fffff7e5cdf8 in stream__on_readable (self=0xaaaaaaaea5f0) at ../neatvnc-0.4.0/src/stream.c:235
#10 0x0000fffff7e5cebc in stream__on_event (obj=0xaaaaaaaebac0) at ../neatvnc-0.4.0/src/stream.c:273
#11 0x0000fffff7e98124 in aml__handle_event (self=0xaaaaaaae8320, obj=0xaaaaaaaebac0) at ../aml-0.2.1/src/aml.c:748
#12 0x0000fffff7e98300 in aml_dispatch (self=0xaaaaaaae8320) at ../aml-0.2.1/src/aml.c:797
#13 0x0000aaaaaaaa75a4 in main (argc=2, argv=0xfffffffff318) at ../wayvnc-0.4.0/src/main.c:1019
```

I'm guessing this is due to some variable being null due to not having loaded anything due to the missing files.

I'm not familiar enough with the code of either wayvnc or xkb to know whether or not it is reasonable to be able to run without it... it may very well be that it can't be expected to work without these files and I should have expected this due to the error message. However, I think that either way, this could be handled better than crashing. I think falling back to some kind of built-in default, typing simply not working, and/or a better warning in the error messages, or adding a hard requirement for the xkeyboard-config package would be an improvement.

After installing the xkeyboard-config package, the error message went away, no more crashes, and works as expected. If I get bored enough I may look deeper into exactly why it's crashing and try to fix it, if someone doesn't beat me to it, though I'm no professional.

...and after having typed all that out, I now realize the fault may actually be in libxkbcommon and nothing is wrong in wayvnc. Now I'm not sure. I guess I'll just put this here for now in case anyone else has this problem or has comments on this.

Edit by any1: Put backtrace in code block

**Comment by any1** [comment]
This is just a missing error check.
