### ISSUE TITLE
Control a computer

### ISSUE THREAD

**Issue by bphd** [any1/wayvnc#138]
Sorry but I tried to read manual, wiki and what I can find on the web and I still don't understand how to use this software

I've 2 computers. On one runs `kwin_wayland` and `sshd`, on the other one `ssh`. I want to be able to see and control some windows or the whole desktop/compositor of the former with the latter. What should I do? Is there a dummy example of a series of commands to achieve that or something?

**Comment by any1** [comment]
Please refer to the first sentence of the first paragraph on the front page: https://github.com/any1/wayvnc#introduction
