### ISSUE TITLE
VSOCK sockets and Hyper-V integration support

### ISSUE THREAD

**Issue by bitthief** [any1/wayvnc#144]
Hi,

I have added support for communicating over VSOCK sockets (on top of the existing TCP and UNIX domain sockets). I developed this for my Hyper-V virtual machines (this is what Hyper-V's "Enhanced sessions" are using in the background), and I was wondering if you and other people would be interested to support this and if I should send a PR with the patches? They're quite small and non-invasive, I followed the UNIX domain sockets implementation from the merged PR last year.

I have been using this successfully for the past few months, performance is much much better compared to TCP, I haven't ran any official benchmarks (no idea what tool to use?), but simply looking at the raw line speeds and using the VM, my guess is that it's at least 20-30x faster than TCP, with much less overhead.

Client-side, I had to patch TigerVNC to support this. On the VM, I'm using sway as the WM in headless mode. While I don't appear to get "full" GPU acceleration (yet), most of the apps are accelerated and using my GPU. I hacked/ported Microsoft's WSLg implementation (dxgkrnl kernel module, MESA with D3D12, nvidia-container-toolkit and the other remaining parts), and browsers etc. are all running as smooth as on the host. As you can see, I'm running this at 2k resolution and it's running at almost native performance, even when the VMs are under heavy load etc.

There is only one minor issue, but my gut feeling is that it's related to the TigerVNC implementation, SSL handshakes are "misbehaving" when enabling authentication and the session doesn't fully establish. It's something to do with some extra bytes or packets not arriving in the correct order (maybe a sync/async blocking/non-blocking socket communication issue). They're not using OpenSSL, it might be a GnuTLS bug. I tried to debug it for a bit when I finished all the patches, but I didn't have time to continue.

![image](https://user-images.githubusercontent.com/29442776/178523310-73fb1934-c76a-4511-acb5-4d3d24a967aa.png)

**Comment by any1** [comment]
Sure, other people might find it useful.

**Comment by any1** [comment]
Closed in favour of #227
