### ISSUE TITLE
Encryption information

### ISSUE THREAD

**Issue by notramo** [any1/wayvnc#147]
Please add info to the readme about encryption:
Does wayvnc use encryption?
When a cert is used, is it encrypted fully or it's only for authentication?
Is it safe to use over e.g. [Yggdrasil](https://yggdrasil-network.github.io/)? Yggdrasil encryption is in alpha stage. Also, every Yggdrasil IP is public.

**Comment by any1** [comment]
Does this not answer your question? https://github.com/any1/wayvnc#encryption--authentication
To be perfectly crystal clear: Yes, you can enable encryption and it's explained in the readme how it can be done.

**Comment by notramo** [comment]
That doesn't answer my questions.
It isn't clear about that only credentials will be encrypted or full stream (screen content, input, etc).
It isn't clear about what encryption method is used. Some encryption methods doesn't protect against MITM.

**Comment by any1** [comment]
It would be a bit silly not encrypting the stream after going through the trouble of setting up encryption, now wouldn't it?

If you want to learn more details, see: https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#subtypes-with-tls-or-x509-prefix

TLS protects against MITM if the certificate is signed by a trusted CA. This can be achieved by having a CA (such as let's encrypt) sign it or importing your own cert into the client. See https://github.com/TigerVNC/tigervnc/wiki/Secure-your-connection

**Comment by notramo** [comment]
Adding these links to the README could be helpful for future users.

I managed to connect securely from TigerVNC `vncviewer`.

However, Remmina client asks me for these:
![image](https://user-images.githubusercontent.com/26059643/182930903-fdea293f-a4ed-4f93-9139-03f61293b166.png)

I guess, according to the TigerVNC wiki, the first (CA cert) is the `cert.pem` generated by the command in the README, because it's self signed.
The second (CRT) is not needed probably.
But what should I do with the third and fourth (client cert and key)?

**Comment by any1** [comment]
> But what should I do with the third and fourth (client cert and key)?

That's for the client to verify its identity to the server. The server does not implement client cert verification, so those do not apply.

**Comment by notramo** [comment]
If I only select the `cert.pem` for the first option, it fails to connect. Is it a bug in Remmina?

**Comment by any1** [comment]
It could be that they just don't support the same authentication scheme. There are some different protocol extensions, and only one of them is implemented for now.

Remmina has two different plugins for VNC. One is based on libvncclient and the other is based on gvnc. Gvnc performs very badly and I would not recommend it. Libvncclient performs ok and supports VeNCrypt, but I don't know if the plugin implements it. The main downside of libvncclient is that the code base is very old and it has been allowed to grow in an organic fashion for a long time and could do with some restructuring.

You can also use SSH forwarding.
