### ISSUE TITLE
Dollar sign ($) does not show up when typing it

### ISSUE THREAD

**Issue by tgharib** [any1/wayvnc#148]
On the server, I am running: `wayvnc 0.0.0.0 -k us`

To confirm the keyboard layout is correct, here is the sway inputs information on the client:

```
owner@Taha-Laptop-Linux ~> swaymsg -t get_inputs
Input device: keyd virtual device
  Type: Keyboard
  Identifier: 4012:2782:keyd_virtual_device
  Product ID: 2782
  Vendor ID: 4012
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled

Input device: keyd virtual pointer
  Type: Mouse
  Identifier: 4012:6878:keyd_virtual_pointer
  Product ID: 6878
  Vendor ID: 4012
  Libinput Send Events: enabled

Input device: ThinkPad Extra Buttons
  Type: Keyboard
  Identifier: 6058:20564:ThinkPad_Extra_Buttons
  Product ID: 20564
  Vendor ID: 6058
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled

Input device: SynPS/2 Synaptics TouchPad
  Type: Touchpad
  Identifier: 2:7:SynPS/2_Synaptics_TouchPad
  Product ID: 7
  Vendor ID: 2
  Libinput Send Events: enabled

Input device: AT Translated Set 2 keyboard
  Type: Keyboard
  Identifier: 1:1:AT_Translated_Set_2_keyboard
  Product ID: 1
  Vendor ID: 1
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled

Input device: Integrated Camera: Integrated C
  Type: Keyboard
  Identifier: 22918:725:Integrated_Camera:_Integrated_C
  Product ID: 725
  Vendor ID: 22918
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled

Input device: Sleep Button
  Type: Keyboard
  Identifier: 0:3:Sleep_Button
  Product ID: 3
  Vendor ID: 0
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled

Input device: Lid Switch
  Type: Switch
  Identifier: 0:5:Lid_Switch
  Product ID: 5
  Vendor ID: 0
  Libinput Send Events: enabled

Input device: Video Bus
  Type: Keyboard
  Identifier: 0:6:Video_Bus
  Product ID: 6
  Vendor ID: 0
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled

Input device: Power Button
  Type: Keyboard
  Identifier: 0:1:Power_Button
  Product ID: 1
  Vendor ID: 0
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled
```

However, when I press Shift+4, nothing appears. 4 by itself works.

**Comment by any1** [comment]
Please tell us the output of `wayvnc -V` and which client you're using.

**Comment by tgharib** [comment]
On the server:

```
owner@Taha-Desktop-Linux ~> wayvnc -V
wayvnc: 0.5.0
neatvnc: 0.5.1
aml: 0.2.2
```

On the client, the issue occurs with both Remmina and RealVNC.

**Comment by awsomearvinder** [comment]
I have the same issue but curiously enough it only seems to occur on XWayland clients. Firefox under X dosen't seem to register my `$`, but firefox under wayland does. Foot (my terminal emulator, wayland) also seems to be fine. I haven't tried any other X clients.
```
wayvnc: 0.5.0
neatvnc: 0.5.1
aml: 0.2.2
```
This issue dosen't really affect me now that I know, but figured the information here might be helpful.

**Comment by any1** [comment]
> I have the same issue but curiously enough it only seems to occur on XWayland clients.

Yeah, that was useful info. I was unable to reproduce this myself with regular wayland clients.

**Comment by any1** [comment]
The `$` symbol gets converted to key code 443 instead of 13 and xwayland doesn't like that. I guess we'll have to set up a quirk table for different keyboard layouts or something...

**Comment by tgharib** [comment]
>Yeah, that was useful info. I was unable to reproduce this myself with regular wayland clients.

Opps, I guess I use a lot of xwayland apps so I didn't realize it didn't happen with regular wayland clients. I can confirm that I can type $ in a wayland client such as foot, qutebrowser, etc.

However, there is one exception where I can reproduce the bug on a wayland client. My `$mod` variable in my sway config is set to the super+shift combo. `set $mod Mod4+shift` I can switch to workspace 1 with Mod4+shift+1, workspace 2 with Mod4+shift+2, etc but I cannot switch to workspace 4 with Mod4+shift+4.
