### ISSUE TITLE
High CPU usage when no clients are connected

### ISSUE THREAD

**Issue by chcore** [any1/wayvnc#149]
Hello,

I have noticed that CPU usage can be quite high even when no clients are connected. This happens with both sway and river (the latter of which doesn't have full damage tracking, which would appear to make the issue worse). Please see https://github.com/riverwm/river/issues/667#issue-1332754856

Is this expected behaviour? Is it possible for wayvnc to be idle when no clients are connected?

**Comment by any1** [comment]
Duplicate of #80

**Comment by chcore** [comment]
For anybody else arriving at this thread concerned about CPU usage, I was able to work around it with systemd socket activation and systemd-socket-proxyd. On my system, wayvnc starts up automatically when a client attempts to connect, and shuts off 5 seconds after the client disconnects.

Only issue remaining is that the first connection attempt always fails (maybe there's a setting somewhere that will address this), but I can live with that for now.
