### ISSUE TITLE
"ERROR: ../src/src/main.c: 605: Failed to start capture. Exiting..." when screen resolution changed while wayvnc is running but no client connected

### ISSUE THREAD

**Issue by Saviq** [any1/wayvnc#152]
Originally reported as MirServer/mir#2571 - more details like wayland-debug can be seen there.

If you change the resolution of a display while wayvnc is running, but no client connected, the next connection will result in an error:

```plain
ERROR: ../src/src/main.c: 605: Failed to start capture. Exiting...
```

Steps to reproduce:
1. start wayvnc
2. resize the shared display
3. connect a client

**Comment by Consolatis** [comment]
Fallout of #150.
Should be fixed with #154, should have tested dimensions changes. Sorry everyone.
