### ISSUE TITLE
Output Scaling

### ISSUE THREAD

**Issue by colemickens** [any1/wayvnc#16]
Output scaling has not been implemented. Trying to run wayvnc with scaled outputs results in errors like these:

TightVNC client: "Error in TightVNC Viewer: Error in protocol size: incorrect size of rectange".

RealVNC: "Attempting to reconnect to VNC Srever... RFB protocol error: bad rectangle: 32x32 at 1760x192 exceeds 1599x899 at 0x0"

Sometimes the bad rectangle is 64x32.

`wlr-randr`:

```
eDP-1 "Sharp Corporation 0x148B 0x00000000 (eDP-1)"
  Physical size: 290x170 mm
  Enabled: no
  Modes:
    3840x2160 px, 59.997002 Hz (preferred)
    3840x2160 px, 47.997002 Hz

```

**Comment by any1** [comment]
It seems that this is just a matter of using the original non-scaled geometry. @colemickens can you confirm?

**Comment by any1** [comment]
Since it works for me, I'll just close this. Feel free to re-open if it's still an issue.
