### ISSUE TITLE
feature request: stop when client disconnect

### ISSUE THREAD

**Issue by rhjdvsgsgks** [any1/wayvnc#170]
hi

im trying to relpace my xvnc+virualgl based remote desktop on a headless machine by wayvnc. after some attempts i found that its much better than former. especially on speed of opengl programs. the only problem is sway will keep running (cpu time increasing) even there is no client connect to wayvnc.

thats why i create #146 . i want wayvnc and sway start when client connect. and stop them after client disconnect. with #146 , they can start when client connect. but will keep running when client disconnect.

after some search. i found that i need to break main loop. but i cant find it by my little bit coding knowledge. could you add a option for it? thanks

**Comment by any1** [comment]
A call to `wayvnc_exit()` will instruct the main loop to exit.

**Comment by any1** [comment]
This can now be implemented using `wayvncctl` to monitor when clients disconnect.

**Comment by pipe01** [comment]
For anyone that comes across this, this bash script will wait for a client to disconnect and close wayvnc when it happens:

```
#!/bin/bash

coproc wayvncctl -j event-receive
grep -m1 client-disconnected <&${COPROC[0]}
[[ $COPROC_PID ]] && kill $COPROC_PID
wayvncctl wayvnc-exit
```
