### ISSUE TITLE
wayvnc stuck at Starting Screen Capture

### ISSUE THREAD

**Issue by gopi487krishna** [any1/wayvnc#172]
Hi 
I have been trying to run wayvnc on my machine but after accepting the client connection wayvnc gets stuck at starting screen capture. 

Platform details:
OS : Gentoo
CPU: Intel core 15 12600K
Graphics : Intel UHD770 ( Integrated )
DIsplay Server : wayland
Window Manager : Hyprland

As wayvnc package on gentoo is old and broken I built wayvnc myself as per the instructions in the README and ran it using the following command :
`build/wayvnc -v 0.0.0.0 `

Output: 

```
Info: Capturing output HDMI-A-2
Info: >> LG Electronics 2D HD LG TV 0x00000101 (HDMI-A-2) 1366x768+0x0
Info: -- LG Electronics LG HDR WFHD 0x000078D9 (HDMI-A-1) 2560x1080+0x0
Info: Listening for connections on 0.0.0.0:5900
Info: New client connection: 0x55bcd72fe250 (ref 1)
Info: Starting screen capture


```
On the client I am using Real VNC viewer

**Comment by any1** [comment]
What is the output from `wayland --version`?

Is there any difference in the output if you run with `--log-level=trace`?

Does the latest released version of wayvnc, neatvnc and aml work for you?

**Comment by gopi487krishna** [comment]
> What is the output from wayland --version?

I am pretty much new to wayland and I dont think i have any application named wayland to check for its version

But here's some information about the window manager and wlroots

**Hyprland Version** : 0.16.0
**wlroots commit id** : 221ee83 ( Bundled within Hyprland. This commit was made just last month (https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/221ee83d440fb7dcbfd141ef3a459a5a973331b6)

> Is there any difference in the output if you run with --log-level=trace?

One Additional line at the bottom :
```
Info: Capturing output HDMI-A-1
Info: >> LG Electronics LG HDR WFHD 0x000078D9 (HDMI-A-1) 2560x1080+0x0
DEBUG: ../subprojects/neatvnc/src/server.c: 1204: Trying address: 0.0.0.0
DEBUG: ../subprojects/neatvnc/src/server.c: 1219: Successfully bound to address
Info: Listening for connections on 0.0.0.0:5900
Info: New client connection: 0x557918b67470 (ref 1)
Info: Starting screen capture
**DEBUG: ../src/main.c: 834: Client connected, new client count: 1**
```


> Does the latest released version of wayvnc, neatvnc and aml work for you?

Yes!! Thanks a lot. Building wayvnc(0.5.0) with latest releases of all the subprojects ( aml - 0.2.2, neatvnc - 0.5.4) resolves the issue and everything works fine.

**Comment by any1** [comment]
Meant to say 'wayvnc --version'
