### ISSUE TITLE
Busylooping/hanging with wayfire in headless

### ISSUE THREAD

**Issue by suncore** [any1/wayvnc#174]
Hi! I'm not at all sure this is a problem in wayvnc but I would like to report it anyway. I have set up wayvnc to start with wayfire in a headless setup. After a short while of using the desktop (like 1 minute), the desktop hangs and wayvnc starts using 100% CPU. I did an strace and this is the result:

rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [INT], 8) = 0
rt_sigprocmask(SIG_SETMASK, [INT], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [INT], 8) = 0
rt_sigprocmask(SIG_SETMASK, [INT], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [INT], 8) = 0
rt_sigprocmask(SIG_SETMASK, [INT], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [INT], 8) = 0
rt_sigprocmask(SIG_SETMASK, [INT], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [INT], 8) = 0
rt_sigprocmask(SIG_SETMASK, [INT], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [INT], 8) = 0
rt_sigprocmask(SIG_SETMASK, [INT], NULL, 8) = 0

Just goes on and on.

**Comment by any1** [comment]
Looks like I broke something in aml. The latest releases of wayvnc+neatvnc+aml should work.
What's the output from `wayvnc --version`?

**Comment by suncore** [comment]
$ /a/linux/labwc/wayvnc/build/wayvnc --version
wayvnc: v0.5.0-17-g8bf5057 (master)
neatvnc: v0.5.1-30-g73e1089 (master)
aml: v0.2.2-8-g0e9eead (master)

**Comment by suncore** [comment]
So far I have identified that it gets stuck in this while loop below

```
EXPORT
void aml_dispatch(struct aml* self)
{
	uint64_t now = aml__gettime_us(self);
	while (aml__handle_timeout(self, now));
```

**Comment by suncore** [comment]
I found that the bug happens because the rate limit is kicking in (I think) and a timer is set in screencopy__start

**Comment by any1** [comment]
This is most likely the culprit: https://github.com/any1/aml/commit/fb2382cb491a7a8b70dfb41dc7371a49230d56b5

**Comment by suncore** [comment]
Thanks!
I added -f1000 to the command line to avoid the timer code. Now it seems to work. I'm not familiar enough with the code to suggest a fix :-)

**Comment by suncore** [comment]
Maybe you can provoke the problem on your side with -f1 or something :-)

**Comment by any1** [comment]
I pushed a fix to aml.

**Comment by suncore** [comment]
Nice! That seems to have fixed it :-)
Thanks!

**Comment by any1** [comment]
Thanks for reporting and debugging.
