### ISSUE TITLE
Feature request: VNC Authentication

### ISSUE THREAD

**Issue by Lorilandly** [any1/wayvnc#176]
Currently wayvnc supports security types of only no encryption or encryption with certificate, and does not support the standard VNC Authentication. When I tryed only setting the password in the configuration file, wayvnc starts up with no encryption.
I understand VNC Authentication is not super secure, but for compatibility reasons I suggest adding support. For example, the vnc client on MacOS only support VNC Authentication. And it is good & simple way for someone who just wants to prevent random people on the local network from accessing the vnc session but doesn't really need security.

**Comment by any1** [comment]
This is intentionally not a feature because it may give some users a false impression of security. It is demonstrably insecure.

Security trumps compatibility.
