### ISSUE TITLE
Option to enforce single client

### ISSUE THREAD

**Issue by suncore** [any1/wayvnc#177]
I usually move between clients when accessing my server (where wayvnc is running). It would be nice with an option to close any existing connection when a new connection comes in.

**Comment by any1** [comment]
You can configure your client to kick out other clients when it connects.

**Comment by suncore** [comment]
Sorry, but how? I have never seen that option. Is it specific to a particular client?

**Comment by any1** [comment]
For TigerVNC the command line flag to share is called `-Shared` and the default behaviour is to not share.

**Comment by suncore** [comment]
Wow, cool, I have been using VNC for forever and always thought this was server side only. Worked fine when I tried it. Thanks! I will close this.
