### ISSUE TITLE
wayvnc 0.1.1 is broken when using scaling

### ISSUE THREAD

**Issue by d4g** [any1/wayvnc#18]
I use sway and have set my internal screen to scale with a factor of 1.5.
When I use wayvnc to capture my screen, the image is disturbed and the VNC connection crashes all the time. I can mitigate the issue by disabling scaling on the captured screen.

**Comment by any1** [comment]
Did you try checking out the master branch?

**Comment by d4g** [comment]
I tired it with version 1.1
https://github.com/NixOS/nixpkgs/blob/b18995ef1002e1047d33c83bd884160825ee5d0a/pkgs/applications/networking/remote/wayvnc/default.nix

**Comment by any1** [comment]
Scaling should be working on the master branch.

**Comment by d4g** [comment]
Ok - I can confirm that scaling seems to be working with the master branch. I still have instability issues but I'm not sure if it is related to the client.

**Comment by any1** [comment]
Which client? Can you be more specific about what constitutes "instability issues"?

**Comment by d4g** [comment]
Sorry - you are right.
Using tightvnc-1.3.10/bin/vncviewer I have constant disconnects.

This looks like that:
```
vncviewer localhost -viewonly                                                                                                                                                                                            ~
Connected to RFB server, using protocol version 3.8
No authentication needed
Authentication successful
Desktop name "WayVNC"
VNC server default format:
  32 bits per pixel.
  Least significant byte first in each pixel.
  True colour: max red 255 green 255 blue 255, shift red 16 green 8 blue 0
Warning: Cannot convert string "-*-helvetica-bold-r-*-*-16-*-*-*-*-*-*-*" to type FontStruct
Using default colormap which is TrueColor.  Pixel format:
  32 bits per pixel.
  Least significant byte first in each pixel.
  True colour: max red 255 green 255 blue 255, shift red 16 green 8 blue 0
Same machine: preferring raw encoding
vncviewer: read: Connection reset by peer
```

This is pretty reproducible and happens - for example - when I move the cursor around.
But using vinagre it is very stable. So this seems to be more of a client issue or probably an issue of the packet.

I discovered another issue and will raise an according ticket.

**Comment by any1** [comment]
tightvnc might be sending some message that wayvnc doesn't know how to interpret, so it closes the connection because it's gone out of sync and everything is bound to be rubbish thereafter. I might look into why this happens on tightvnc.

Anyhow, tightvnc doesn't really work very well with wayvnc because tight encoding is not really supported by wayvnc at the moment, meaning that network traffic will be very high due to raw encoding being used.

Remmina, real vnc and tigervnc support ZRLE, which is implemented in wayvnc

**Comment by d4g** [comment]
Perfect - thanks. I switched to tigervnc for now, which seems to work great.
