### ISSUE TITLE
cannot connect - wayvnc not opening a port

### ISSUE THREAD

**Issue by RolandWarburton** [any1/wayvnc#184]
Hi All,

I am having some trouble getting wayvnc working with sway on debian 11.

I have built wayvnc from source using the script in the README on Debian 11 (bullseye).

When I run `./build/wayvnc --log-level=info 0.0.0.0` I see no output from wayvnc, is this expected?

I also see no port being opened, nor can I connect from either the local machine or other machines in the same network.

```none
~ ❯ sudo lsof -i -P -n | grep LISTEN
sshd       432   root    3u  IPv4  10777      0t0  TCP *:22 (LISTEN)
sshd       432   root    4u  IPv6  10779      0t0  TCP *:22 (LISTEN)
```

There are also nothing output to stdout even with the log level set.

Any ideas on whats wrong here?

Thanks!

**Comment by any1** [comment]
Maybe try setting log level to `trace`?

Otherwise, `strace` might help.

By the way, there is a shorter command to check for listening tcp sockets that also doesn't require root. Depending on your system, it is either `ss -ntl` or `netstat -ntl`.

**Comment by RolandWarburton** [comment]
Thanks for your help, yes I do see the output with `trace` after a reboot and everything is working as expected.
