### ISSUE TITLE
High CPU usage when wayvnc is capturing an output that is "DPMS off"

### ISSUE THREAD

**Issue by lack** [any1/wayvnc#194]
How to replicate:
- Start wayvnc
- Measure CPU usage (minimal)
- turn screens off with `swaymsg output '*' DPMS off`
- Connect a VNC client
- Measure CPU usage. I see sway and wayvnc using ~50% of a single core, each.
- turn screens on with `swaymsg output '*' DPMS on` or disconnect the client
- Measure CPU usage (much lower)

**Comment by lack** [comment]
After running some profiling it looks like wayvnc gets stuck in a pretty tight loop when an output is DPMS off and a client connects:
- we start a screen capture via `wayvnc_start_capture_immediate`
- the capture fails and we get the `screencopy_failed` callback
- we see the `SCREENCOPY_FAILED` state in `on_capture_done` which immediately tries again by calling `wayvnc_start_capture_immediate`...

**Comment by Consolatis** [comment]
I wonder though if this highlights an issue in wlroots. Shouldn't the screencapture keep working even though the physical output is turned off?

**Comment by lack** [comment]
A great question.  I'll ask it and see if anyone answers.

@any1 : Does your upstream Wayland capture protocol proposal specify what its behavior should be, if an output is in "low power mode"?
