### ISSUE TITLE
Don't work on sway?

### ISSUE THREAD

**Issue by felixsanz** [any1/wayvnc#223]
Executing the command with `wayvnc -L debug 0.0.0.0 5900` or even adding `-s seat0` doesn't seem to work fine.

No error is printed and port seems to be used:

```
tcp        0      0 0.0.0.0:5900            0.0.0.0:*               LISTEN      243267/wayvnc        off (0.00/0/0)
```

But when I connect, all the applications I tried just say "unable to connect", and wayvnc prints:

```
Info: New client connection: 0x5563b8488bd0 (ref 1)
Info: Closing client connection 0x5563b8488bd0: ref 0
```

For every new try, that happens over and over again. What is the error then?

**Comment by felixsanz** [comment]
This has been fixed when using the latest git version, but there is a lot of errors, seg faults, weird colors when you are lucky to connect... :/

**Comment by lack** [comment]
You may get more output with the git build if you run with `-L trace`

Also, which clients have you tried?

**Comment by lack** [comment]
And we could probably look at the errors, if you'd like to post some?

**Comment by felixsanz** [comment]
> And we could probably look at the errors, if you'd like to post some?

it's just a segmentation fault, there is no error output :/ Anyway i don't think this is going to work. Even when it do... everything is blue and corrupted/weird. I'll wait a bit more, wayland is hell atm

**Comment by lack** [comment]
If you run with `-L trace` there may be a bit more context before the segfault, but the best thing to track down a segfault would be to run in gdb and get a backtrace when it crashes.

**Comment by any1** [comment]
> I'll wait a bit more, wayland is hell atm

What do you think would happen in the world if everyone waited for everyone else to fix things?

It seems to me that you've only come here to complain, rather than help out. If you want to help, please give us the following information:
 * Output from `wayvnc -v`
 * Output from `sway -v`
 * Trace logs
 * Backtrace

**Comment by felixsanz** [comment]
Sorry but I don't have currently time to backtrace segmentation faults. I'll reopen the issue when I find spare time.

If my message was not understood, I said "wayland is hell atm", not wayvnc. Of course I can help debug/fix wayvnc, but guess what? This probably has nothing to do with wayvnc. Nvidia broke their EGL rendering in the latest drivers update, I'm having a ton of flickering, etc. Wayland is the problem here, so I just said that i'll wait a bit more for it to mature, and then I'll re-take a look at wayvnc and why it don't works.

I'm having a lot of issues, like vscode scrolling jumping around, etc. I just can't spend days fixing every app because wayland is still very alpha. Hope you can understand why I don't want to continue backtracing just yet.
