### ISSUE TITLE
Can't build git version on arch

### ISSUE THREAD

**Issue by felixsanz** [any1/wayvnc#224]
Basically wayvnc-git needs aml-git (not aml), but when you install the package...

```
:: Checking for conflicts...
:: Checking for inner conflicts...
 -> Package conflicts found:
 -> Installing aml will remove: aml-git (aml)
```

So...

**Comment by felixsanz** [comment]
I think the problem is aml-git not having `provides=(libaml.so)`

**Comment by felixsanz** [comment]
The problem is aml provides "libaml.so" and aml-git provides "aml".

Both neatvnc-git and wayvnc-git needs libaml.so, so only `aml` can satisfy. Modiying both PKGBUILD to depend on `aml` instead of `libaml.so` fixes it.

**Comment by lack** [comment]
Have you reported this issue to the Arch package maintainer?

**Comment by lack** [comment]
Though it does look like this change by @any1 may have broken the deps there? https://aur.archlinux.org/cgit/aur.git/commit/?h=wayvnc-git&id=c8daf8c07c927b927e6c7d48a3deac714b53e547

Perhaps this is better handled at https://aur.archlinux.org/packages/wayvnc-git

**Comment by any1** [comment]
I think the issue is really with "aml-git", which I don't have control over (currently). But I've replaced "libaml.so" with "aml" for now.
