### ISSUE TITLE
systemd untification troubles

### ISSUE THREAD

**Issue by cherusk** [any1/wayvnc#23]
I'm trying to wrap wayvnc into a systemd unit, but it bulges for:

> 07:02:00 Tue Mar 17 jobs:1 root@ punraz :~# systemctl status wayvnc
> ● wayvnc.service - "Wayland VNC server"
>    Loaded: loaded (/etc/systemd/user/wayvnc.service; enabled; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Tue 2020-03-17 07:02:00 CET; 2s ago
>   Process: 6894 ExecStart=/usr/local/bin/wayvnc --config=${CNFG_FILE} (code=exited, status=1/FAILURE)
>  Main PID: 6894 (code=exited, status=1/FAILURE)
> 
> Mar 17 07:02:00 punraz systemd[1]: Started "Wayland VNC server".
> Mar 17 07:02:00 punraz wayvnc[6894]: error: XDG_RUNTIME_DIR not set in the environment.
> Mar 17 07:02:00 punraz wayvnc[6894]: ERROR: Failed to initialise wayland
> Mar 17 07:02:00 punraz systemd[1]: wayvnc.service: Main process exited, code=exited, status=1/FAILURE
> Mar 17 07:02:00 punraz systemd[1]: wayvnc.service: Failed with result 'exit-code'.

That's the unit definition:

> # cat /etc/systemd/user/wayvnc.service
> 
> [Unit]
> Description="Wayland VNC server"
> 
> [Service]
> Environment="CNFG_FILE=/usr/local/etc/wayvnc.cnfg"
> ExecStart=/usr/local/bin/wayvnc --config=${CNFG_FILE}
> 
> [Install]
> WantedBy=multi-user.target

When I run wayvnc from unpriviliged user it works better. Unpriviliged apparently has **XDG_*** **environment variables** set.

When I transported these **environment variables** to the systemd unit into its **Environment=**, I still ran into issues.

Please advice.

**Comment by any1** [comment]
AFAIK, wayland requires clients to run as the same user as the compositor. Please, ask support questions on IRC. The issue tracker is for bugs and feature requests.
