### ISSUE TITLE
[0.6.2] Quality regression with vncviewer

### ISSUE THREAD

**Issue by bhepple** [any1/wayvnc#238]
Not sure if this belongs with **neatvnc** ... but the only way I can reproduce it is with **wayvnc**, so here it is.

Please see the attached images. There seems to be a problem with **vncviewer** from **tigervnc** connecting to **wayvnc** running against a headless sway session. This is on up to date fedora-37 systems.

**vncviewer** attached to wayvnc-0.5.0:

![wayvnc-0 5 0](https://user-images.githubusercontent.com/6417002/216210471-2976afe0-bda3-416e-8df8-d1431d657344.png)

vncviewer attached to wayvnc-0.6.2:

![wayvnc-0 6 2](https://user-images.githubusercontent.com/6417002/216210548-1dd6a98a-c18f-4ad4-86cc-17cf8e48e217.png)

On the headless session, I have:

```
$ swaymsg -t get_outputs
Output HEADLESS-1 'headless headless ' (focused)
  Current mode: 1920x1080 @ 60.000 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown <<< I've tried with 'rgb' as well - same difference
  Transform: normal
  Workspace: 1
  Max render time: off
  Adaptive sync: disabled
```

It doesn't appear to be a problem on a 'real' remote session ie running on a physical monitor:

```
$ swaymsg -t get_outputs
Output HDMI-A-1 'Samsung Electric Company SAMSUNG 0x00000F00' (focused)
  Current mode: 1920x1080 @ 60.000 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: rgb
  Transform: normal
  Workspace: 3:foot
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    1920x1080 @ 60.000 Hz
    1920x1080 @ 59.940 Hz
    1920x1080 @ 50.000 Hz
    1920x1080 @ 30.000 Hz
    1920x1080 @ 29.970 Hz
    1920x1080 @ 25.000 Hz
    ./etc
```

Using **remmina** instead of **vncviewer** seems to fix the problem, so that's a workaround.

```
sway-1.7-4.fc37.x86_64
wlroots-0.16.1-1.fc37.x86_64
tigervnc-1.12.0
waybar-0.9.16-1.fc37.x86_64
```

**Comment by any1** [comment]
You can adjust the quality level from your client.

**Comment by bhepple** [comment]
Thanks for the insight.

It's just a bit weird that -QualityLevel=9 was not needed in 0.5.0 but is needed in 0.6.2

Oh well, if anyone else notices this, the answer is given!!

**Comment by any1** [comment]
Quality settings didn't work properly before.
