### ISSUE TITLE
Client-side Scaling?

### ISSUE THREAD

**Issue by Arkwin** [any1/wayvnc#240]
I am trying to figure how to adjust client-side scaling.  I am using TigerVNC to connect to my Linux phone and it works amazing, but the screen size is huge and puts scroll bars on the window. 

The xrandr shows 360x720, 320x240, 320x200 as options, but under settings and display it should 720x1440. Both of which should be able to show up on a 4k screen without scroll bars or anything. 

Resizing the window doesn't do any sort of autos-scaling or anything.

TigerVNC viewer on windows 11 or Pop_OS 22.04 do noes not change. 

Thank you for your time.

**Comment by any1** [comment]
Duplicates #57
