### ISSUE TITLE
undefined symbol: nvnc_set_cut_text_receive_fn

### ISSUE THREAD

**Issue by crashbit666** [any1/wayvnc#247]
### Useful information:
Please, try to gather as much of useful information as possible.

- **Version:**
  - `wayvnc -V`
  - 0.5.0-1 Manjaro

Before wayvnc works perfect. But today I can see it doesn't run

wayvnc: symbol lookup error: wayvnc: undefined symbol: nvnc_set_cut_text_receive_fn

It happens  on manjaro sway on rpi4 with 8GB ram

![20230409_15h37m57s_grim](https://user-images.githubusercontent.com/6796939/230775999-bf9aa19a-a0c4-4276-9460-2bd70229d66c.png)

**Comment by any1** [comment]
You need to upgrade neatvnc and probably also aml.

**Comment by crashbit666** [comment]
> You need to upgrade neatvnc and probably also aml.

Ok, I will do

**Comment by crashbit666** [comment]
I'm using this versions of neatvnc and aml:

 crashbit@rpi4-pos    pacman -Si neatvnc
Repositori              : community
Nom                     : neatvnc
Versió                  : 0.6.0-1
Descripció              : Fast and neat VNC server library
Arquitectura            : aarch64
URL                     : https://github.com/any1/neatvnc

 crashbit@rpi4-pos    pacman -Si aml
Repositori              : community
Nom                     : aml
Versió                  : 0.3.0-1
Descripció              : Another Main Loop
Arquitectura            : aarch64
URL                     : https://github.com/any1/aml

I think I'm using latest releases

**Comment by any1** [comment]
If you're still having this problem, run `ldd` or `libtree` on `/usr/bin/wayvnc` to see if it's linked to something unexpected.

**Comment by crashbit666** [comment]
I'm attach ldd /usr/bin/wayvnc

[ldd.wayvnc.txt](https://github.com/any1/wayvnc/files/11396055/ldd.wayvnc.txt)
