### ISSUE TITLE
None of the encoders work

### ISSUE THREAD

**Issue by TheImunityGamer** [any1/wayvnc#255]
### Useful information:
Please, try to gather as much of useful information as possible and follow
these instructions:

- **Version:**
  - Run this command: `wayvnc -V`
  - I used `./build/wayvnc -V` instead
  - wayvnc: v0.6.2-30-g945f590 (master)
    neatvnc: v0.6.0-28-gade1046 (master)
    aml: v0.3.0-1-gede4249 (master)

- Try to reproduce while capturing a **trace log:**
  - `wayvnc -Ltrace | tee wayvnc-crash.log`
  - Used `./build/wayvnc 0.0.0.0 -Ltrace --gpu | tee wayvnc-crash.log`

```
TRACE: ../src/main.c: 234: Registering new wlr_output_power_manager
TRACE: ../src/main.c: 224: Registering new xdg_output_manager
TRACE: ../src/main.c: 205: Registering new output 46
TRACE: ../src/output.c: 222: Output 46 name: HDMI-A-1
TRACE: ../src/output.c: 231: Output 46 description: Samsung Electric Company LS24AG30x H4PR700788 (HDMI-A-1)
TRACE: ../src/output.c: 274: Output HDMI-A-1 power state changed to ON
Info: Capturing output HDMI-A-1
Info: >> Samsung Electric Company LS24AG30x H4PR700788 (HDMI-A-1) 1920x1080+0x0 Power:ON
DEBUG: ../subprojects/neatvnc/src/server.c: 1341: Trying address: 0.0.0.0
DEBUG: ../subprojects/neatvnc/src/server.c: 1361: Successfully bound to address
Info: Listening for connections on 0.0.0.0:5900
DEBUG: ../src/ctl-server.c: 751: Initializing wayvncctl socket: /run/user/1000/wayvncctl
Info: New client connection from *redacted*: 0x55ac80362ae0 (ref 1)
Info: Starting screen capture
DEBUG: ../src/main.c: 1100: Client connected, new client count: 1
DEBUG: ../src/ctl-server.c: 879: Enqueueing client-connected event: {"id":"1","hostname":"*redacted*","username":null,"seat":"seat0","connection_count":1}
DEBUG: ../src/ctl-server.c: 906: Enqueued client-connected event for 0 clients
Info: Choosing tight encoding for client 0x55ac80362ae0
```
Final error that didn't make it into the log:
```
fish: Process 502385, './build/wayvnc' from job 2, './build/wayvnc 0.0.0.0 -Ltrace …' terminated by signal SIGSEGV (Address boundary error)
```

- Using raw encoding the last two bits are different:
```
Info: Choosing raw encoding for client 0x5580b00c8ee0
wayvnc: ../subprojects/neatvnc/src/raw-encoding.c:151: raw_encoder_do_work: Assertion `rc == 0' failed.
fish: Job 2, './build/wayvnc 0.0.0.0 -Ltrace …' terminated by signal SIGABRT (Abort)
```

- And using zrle encoding:
```
Info: Choosing zrle encoding for client 0x55fd9f6a4ee0
wayvnc: ../subprojects/neatvnc/src/zrle.c:354: zrle_encoder_do_work: Assertion `rc == 0' failed.
fish: Job 2, './build/wayvnc 0.0.0.0 -Ltrace …' terminated by signal SIGABRT (Abort)
```

- Get the **stack trace**:
  - If have `coredumpctl`, you can gather the stack trace after a crash using
    `coredumpctl gdb wayvnc` and then run `bt full` to obtain the stack trace.
  - Otherwise, you can either locate the core file and load it into gdb or run
    wayvnc in gdb like so:
    - `gdb --args wayvnc -Ltrace`
  - If the lines mentioning wayvnc, neatvnc or aml have `??`, please compile
    wayvnc and those other projects from source with debug symbols and try
    again.
  - Couldn't figure this out, sorry.

- Describe how to **reproduce** the problem
I'm on Hyprland + Arch. I applied [this patch](https://github.com/any1/wayvnc/issues/248#issuecomment-1519036469) to fix the SIGSEGV issue with zrle. I just changed the code in the way they recommended and configured and built the project. Don't know how to patch. I'm using TigerVNC on a seperate device because I can set the encoding in it.

I am hoping to get an encoding working. Getting the rc to not be 0 when using zrle would be the best case scenario. I can provide more info if you need.

**Comment by any1** [comment]
Probably failed to map the frame buffer. Have you tried without `--gpu`?

**Comment by TheImunityGamer** [comment]
I have now. Still getting the assert issue on line 350 with zrle.

**Comment by any1** [comment]
Yeah, you most likely have 24 bit pixel buffers. That won't work.

**Comment by TheImunityGamer** [comment]
How can I disable them?

**Comment by any1** [comment]
I don't know if you can select different pixel formats with Nvidia. In any case, non-free graphics drivers are not supported. I will accept pull requests for 24 bit pixel buffers, but I am not interested in doing this myself for now.
