### ISSUE TITLE
Allow to poll client side canvas resolution from wayvncctl

### ISSUE THREAD

**Issue by wucke13** [any1/wayvnc#259]
If there would be a `wayvncctl` command to get the current resolution of the VNC client canvas, it would be trivial to enable automatic resolution change upon resizing of the client window. Even better would be, if resolution changes of the client create events in `wayvncctl`.

**Comment by any1** [comment]
The same can also the achieved using `wlr-output-management-unstable-v1` in a way that doesn't require user scripting.

**Comment by lirannl** [comment]
I've seen that one, but how is that protocol used? Is it just supposed to be seamless? Is there a generic wlroots function for resizing a display? I'm running 0.8-rc0 on Hyprland, but it's not working

**Comment by any1** [comment]
> I've seen that one, but how is that protocol used? Is it just supposed to be seamless? Is there a generic wlroots function for resizing a display? I'm running 0.8-rc0 on Hyprland, but it's not working

This was implemented recently, but it only works with headless outputs. The output name needs to start with "HEADLESS-".

**Comment by any1** [comment]
Being that this is already implemented via output-management, I'll be closing this.
