### ISSUE TITLE
Segmentation Fault on Arch on Wayfire when connecting with RealVNC or TigerVNC

### ISSUE THREAD

**Issue by kode54** [any1/wayvnc#265]
### Useful information:
- **Version:**
wayvnc: v0.8-dev-1c489ad (master)
neatvnc: v0.8-dev-6beb263 (master)
aml: v0.3.0-0-gb83f357 (makepkg)

I already traced what causes it: Several instances in WayVNC main.c that dereference a null `struct seat *` to `->name` and pass that on. I'll submit a PR that checks these.

**Comment by any1** [comment]
Fixed!
