### ISSUE TITLE
Wayvnc crashes on old Linux kernels without memfd_create support

### ISSUE THREAD

**Issue by acozzette** [any1/wayvnc#267]
Yesterday I tried running wayvnc on an older Android phone and found that it crashed due to lack of support for the memfd_create system call in the Linux kernel. My phone's kernel is based on 3.10 and memfd_create was added in 3.17. The memfd_create() function exists in libc but it always returns a "not implemented" error here: https://github.com/any1/wayvnc/blob/27cd6351be6ec023cc562018cd44d7c5a3816c26/src/shm.c#L51 (Sorry I didn't save the exact error message, but I could try again and save it if that if it would help.)

I was thinking a good way to solve it would be to just update `create_shm_file()` to try the fallback code path if `memfd_create()` fails. If that sounds OK then I could try sending out a pull request with that change.

**Comment by any1** [comment]
There's no harm in trying a fallback if memfd fails, but this isn't really a bug. If you don't compile using 3.10 kernel headers, you can't really expect things to work with 3.10.

**Comment by acozzette** [comment]
Thank you for the feedback. After thinking about this some more, I think it's probably better actually to just write a simple polyfill for memfd_create and use `LD_PRELOAD` to override the function from libc. I will go ahead and do that and just close this issue.
