### ISSUE TITLE
mouse on client device doesn't match on server device with 2 monitors

### ISSUE THREAD

**Issue by mrsteve0924** [any1/wayvnc#273]
- **Version:**
  wayvnc: v0.8-dev-27cd635 (master)
neatvnc: v0.8-dev-6beb263 (master)
aml: v0.3.0-0-gb83f357 (makepkg)

client device shows just one monitor as it should but mouse on server scrolls over both monitors so difficult to select anything.
might be same issues as #8 #64 #256 ?

im using wayfire and realvnc viewer

**Comment by any1** [comment]
Yes, this is still an issue with wayfire,

**Comment by mrsteve0924** [comment]
> Yes, this is still an issue with wayfire,

i'll have to push wayfire to address it . thanks
