### ISSUE TITLE
Unneccesary dns lookup when client connects

### ISSUE THREAD

**Issue by bhepple** [any1/wayvnc#274]
Approx 30-40s delay when trying to connect to a wayvnc

Remote server is fedora-38 running sway:
wayvnc: 0.6.0
neatvnc: 0.7.0
aml: 0.3.0
sway-1.8.1-1.fc38.x86_64

- Describe how to **reproduce** the problem

On the server:
Running wayvnc -Ltrace 0.0.0.0 5900

On a laptop over wifi:

vncviewer nina:5900
or
remmina  vnc://nina:5900

Output:
```
Info: Capturing output HDMI-A-1
Info: >> Samsung Electric Company SAMSUNG 0x00000F00 (HDMI-A-1) 1920x1080+0x0 Power:ON
DEBUG: ../src/server.c: 1805: Trying address: 0.0.0.0
DEBUG: ../src/server.c: 1825: Successfully bound to address
Info: Listening for connections on 0.0.0.0:5900
DEBUG: ../src/ctl-server.c: 724: Initializing wayvncctl socket: /run/user/500/wayvncctl
DEBUG: ../src/ctl-server.c: 693: Connecting to existing socket in case it's stale
DEBUG: ../src/ctl-server.c: 700: Connect failed: Connection refused
Warning: ../src/ctl-server.c: 703: Deleting stale control socket path "/run/user/500/wayvncctl"

               <.... 30-40s delay here ...>

Info: New client connection from 192.168.0.118: 0x56493986aba0 (ref 1)
DEBUG: ../src/server.c: 788: Client chose security type: 1
Info: Starting screen capture
DEBUG: ../src/main.c: 1069: Client connected, new client count: 1
DEBUG: ../src/ctl-server.c: 849: Enqueueing client-connected event: {"id":"1","hostname":"192.168.0.118","username":null,"connection_count":1}
DEBUG: ../src/ctl-server.c: 876: Enqueued client-connected event for 0 clients
Info: Choosing tight encoding for client 0x56493986aba0
Info: Client 0x56493986aba0 (1) hung up
Info: Closing client connection 0x56493986aba0: ref 0
DEBUG: ../src/main.c: 1036: Client disconnected, new client count: 0
DEBUG: ../src/ctl-server.c: 849: Enqueueing client-disconnected event: {"id":"1","hostname":"192.168.0.118","username":null,"connection_count":0}
DEBUG: ../src/ctl-server.c: 876: Enqueued client-disconnected event for 0 clients
Info: Stopping screen capture
```

Same problem, similar delay with vncviewer or remmina - kinda sorta points the bone at wayvnc.

The magnitude of the delay suggests a portal timeout but I see no relevant activity with dbus-monitor.

**Comment by any1** [comment]
That looks like a network issue. Can you run in `strace`?

**Comment by any1** [comment]
Also, wayvnc v0.6.0 and neatvnc v0.7.0 is an odd combo.

**Comment by bhepple** [comment]
I updated to wayvnc-0.7.1 but same problem.

Attaching the output from 
```
strace wayvnc -Ltrace 0.0.0.0 5900
```

The pause happens at a call to ppoll() at line 3064 - could that be a DNS resolver issue?

[wayvnc.log](https://github.com/any1/wayvnc/files/13237915/wayvnc.log)

**Comment by bhepple** [comment]
Yes it is the resolver!! It's trying to do (effectively):
```
nslookup 192.168.0.118
```
ie reverse DNS lookup on the client (my laptop). But since I don't have it in a local DNS lookup, it times out. If I put an entry into /etc/hosts for my laptop, it prevents the delay. I guess that fixes my problem but it's a bit awkward to arrange DNS lookups in a dhcp network.

The question asks itself "why does wayvnc do that lookup, and is it really necessary". I can't answer that one!

**Comment by Consolatis** [comment]
> The question asks itself "why does wayvnc do that lookup, and is it really necessary". I can't answer that one!

My 2 cents: It's not necessary. If a client using wayvncctl wants to know the hostname it can do the reverse lookup itself without blocking wayvnc.

**Comment by any1** [comment]
> > The question asks itself "why does wayvnc do that lookup, and is it really necessary". I can't answer that one!
> 
> My 2 cents: It's not necessary. If a client using wayvncctl wants to know the hostname it can do the reverse lookup itself without blocking wayvnc.

Yeah, I agree.

**Comment by any1** [comment]
I removed the DNS lookup in neatvnc, so it will now just return the IP address instead. At some point, I might add the lookup to `wayvncctl`.

**Comment by bhepple** [comment]
Rebuilt wayvnc-0.7.2 and neatvnc-0.7.1 on fedora-38. Works well (without the entry in /etc/hosts). Looks like a fix.
