### ISSUE TITLE
Segmentation Fault which happens when connecting

### ISSUE THREAD

**Issue by eksno** [any1/wayvnc#276]
### Discussed in https://github.com/any1/wayvnc/discussions/275

<div type='discussions-op-text'>

<sup>Originally posted by **eksno** November  2, 2023</sup>
## System Details:

Nvidia with open source kernel module (not to be confused with the independent third-party "nouveau" open source driver).

OS: NixOS 23.11.20231029.0cbe9f6 (Tapir) x86_64 
Kernel: 6.1.60 
Shell: fish 3.6.1 
DE: Hyprland (Wayland) 
WM: .Hyprland-wrapp 
Terminal: kitty 
CPU: AMD Ryzen 5 1600 (12) @ 3.200GHz 
GPU: NVIDIA GeForce RTX 2070

### Source

- Query: https://search.nixos.org/packages?channel=unstable&show=wayvnc&from=0&size=50&sort=relevance&type=packages&query=wayvnc
- Source: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/networking/remote/wayvnc/default.nix

### Version

```
eksno@verse ~> wayvnc -V
wayvnc: 0.7.1
neatvnc: 0.7.0
aml: 0.3.0
```

## Logs

```
eksno@verse ~> wayvnc 0.0.0.0 -L trace
Info: Capturing output HDMI-A-1
Info: >> ASUSTek COMPUTER INC ASUS VG249 0x00016215 (HDMI-A-1) 1920x1080+0x0 Power:ON
DEBUG: ../src/server.c: 1805: Trying address: 0.0.0.0
DEBUG: ../src/server.c: 1825: Successfully bound to address
Info: Listening for connections on 0.0.0.0:5900
DEBUG: ../src/ctl-server.c: 751: Initializing wayvncctl socket: /run/user/1000/wayvncctl
Info: New client connection from WPF31R143.home: 0x1bbe630 (ref 1)
DEBUG: ../src/server.c: 788: Client chose security type: 1
Info: Starting screen capture
DEBUG: ../src/main.c: 1139: Client connected, new client count: 1
DEBUG: ../src/ctl-server.c: 879: Enqueueing client-connected event: {"id":"1","hostname":"WPF31R143.home","username":null,"seat":"seat0","connection_count":1}
DEBUG: ../src/ctl-server.c: 906: Enqueued client-connected event for 0 clients
Info: Choosing zrle encoding for client 0x1bbe630
fish: Job 1, 'wayvnc 0.0.0.0 -L trace' terminated by signal SIGSEGV (Address boundary error)
```</div>

**Comment by any1** [comment]
Duplicate of #248? If not, a backtrace would be helpful.

**Comment by eksno** [comment]
> Duplicate of #248? If not, a backtrace would be helpful.

That's correct, backtrace looks the exact same! Thanks for the help.

Saw their logs had a seemingly different error when looking for similar issued, so I had overlooked that, but it was just environment difference.

Quite new to nixos and wayland 😄 so thanks for making my life that much easier. Now to figure out compiling from source with nixos hehe
