### ISSUE TITLE
Bind to other address than 0.0.0.0 fails, if defined in config file

### ISSUE THREAD

**Issue by cRoCx** [any1/wayvnc#284]
The config file doesn't seem to accept addresses other than `0.0.0.0`. Tried it with `localhost`, `192.168.0.0`, `192.168.0.100` (own ip address), `::1` and `localhost,192.168.0.100,2466:44:2234::100`.

- **Version:**
wayvnc: 0.7.2
neatvnc: 0.7.1
aml: 0.3.0

- Try to reproduce while capturing a **trace log:**
  - `wayvnc -Ltrace | tee wayvnc-crash.log`
  - Output:
> error: XDG_RUNTIME_DIR is invalid or not set in the environment.
> ERROR: ../src/main.c: 402: WAYLAND_DISPLAY is not set in the environment
> ERROR: ../src/main.c: 1495: Failed to initialise wayland

- Describe how to **reproduce** the problem
Fresh install of Raspberry Pi OS Bookworm on Raspberry Pi 5. Enabled VNC via `raspi-config` (enables wayvnc). In `/home/username/.config/wayvnc/config` changed `address=0.0.0.0` to `address=192.168.0.0` or anything else. Restart (`sudo reboot`).

My goal was actually to try binding to `localhost`, a custom IPv4 VPN address and another custom IPv6 VPN address (`address=localhost,192.168.0.100,2466:44:2234::100`) and then disable the authentication. I wanted to test this, since `address=0.0.0.0` and adding `user=test` and `pw=test` also doesn't work. The latter is another problem I might report later in a seperate issue.

The only combination that works is `address=0.0.0.0` and having `enable_auth=` either `true` with default certificates and default user auth (no seperate credentials in config file) or `false`.

**Comment by any1** [comment]
Setting any address that is assigned to my host works fine for me. Setting an address range like `192.168.0.0` won't work. It doesn't know that you're trying to say `192.168.0.0/24` (which it doesn't know how to parse either).

I've been meaning to add the ability to bind to multiple addresses, but that is not supported as is.
