### ISSUE TITLE
Keyboard cannot input anything on lock screen

### ISSUE THREAD

**Issue by ystyle** [any1/wayvnc#289]
### Useful information:
Please, try to gather as much of useful information as possible and follow
these instructions:

- **Version:**
  - Run this command: `wayvnc -V`
```
wayvnc: v0.7.2-0-g4de85ac (makepkg)
neatvnc: v0.7.1-0-gb5b330b (makepkg)
aml: v0.3.0-0-gb83f357 (makepkg)

DE: hyprland/wayland
Screen lock:  waylock
OS: archlinux 
```

- Try to reproduce while capturing a **trace log:**
  - `wayvnc -Ltrace | tee wayvnc-crash.log`
```shell
╰━  wayvnc -Ltrac
Info: Capturing output DP-1
Info: >> Dell Inc. DELL P2317H KGR9N762369B (DP-1 via HDMI) 1920x1080+0x0 Power:ON
Info: -- AU Optronics 0x282B (eDP-1) 3840x2160+0x0 Power:ON
DEBUG: ../neatvnc/src/server.c: 1813: Trying address: 10.0.7.7
DEBUG: ../neatvnc/src/server.c: 1833: Successfully bound to address
Info: Listening for connections on 10.0.7.7:5900
DEBUG: ../wayvnc/src/ctl-server.c: 754: Initializing wayvncctl socket: /run/user/1000/wayvncctl
Info: New client connection from 10.0.7.3: 0x617e988db8a0 (ref 1)
DEBUG: ../neatvnc/src/server.c: 789: Client chose security type: 1
Info: Starting screen capture
DEBUG: ../wayvnc/src/main.c: 1143: Client connected, new client count: 1
DEBUG: ../wayvnc/src/ctl-server.c: 882: Enqueueing client-connected event: {"id":"1","hostname":"10.0.7.3","username":null,"seat":"seat0","connection_count":1}
DEBUG: ../wayvnc/src/ctl-server.c: 909: Enqueued client-connected event for 0 clients
Info: Choosing tight encoding for client 0x617e988db8a0
```

- Get the **stack trace**:
  - If have `coredumpctl`, you can gather the stack trace after a crash using
    `coredumpctl gdb wayvnc` and then run `bt full` to obtain the stack trace.
  - Otherwise, you can either locate the core file and load it into gdb or run
    wayvnc in gdb like so:
    - `gdb --args wayvnc -Ltrace`
  - If the lines mentioning wayvnc, neatvnc or aml have `??`, please compile
    wayvnc and those other projects from source with debug symbols and try
    again.

- Describe how to **reproduce** the problem
  - on archlinux 
    - export WAYLAND_DISPLAY=wayland-1
    - wayvnc
  - use TightVNC viewer connect to archlinux  on windows 11
  - first can connected and unlock the screen. close  TightVNC viewer
  - reconnect, then the keyborad can not input any thing on lock screen

**Comment by any1** [comment]
@vaxerski Any thoughts on this? Does Hyprland maybe block virtual inputs when the screen is locked?

**Comment by vaxerski** [comment]
no thoughts on this. I am focusing on other things. Feel free to make a mr

**Comment by vaxerski** [comment]
skimmed over the code, doesn't seem to have anything of note to block virtual keyboards on lockscreens. Might be something I'm missing though, as usual.

**Comment by any1** [comment]
@ystyle, is this still a problem?

**Comment by ystyle** [comment]
It's OK now
