### ISSUE TITLE
swaymsg output and automatic server-side resizing not working on wayvnc 0.8 + sway < 1.9

### ISSUE THREAD

**Issue by alexcaoys** [any1/wayvnc#298]
### Some Background

I was using my Raspberry Pi as a wayvnc server for a few months now (installed from apt). Recently I heard v0.8 adds the support for **"Automatic server-side resizing of headless outputs"**, which I've been using before with X11+tigervnc. So I checked it out, but it was not usable, at least not on my setup. So I went down this rabbit hole and here's what I found. 

### Setup

sway was installed from apt, set up using systemd user unit with `Environment="WLR_BACKENDS=headless" "WLR_LIBINPUT_NO_DEVICES=1"`
Previously I was using wayvnc 0.6 from apt, I will refer to it as the **apt** version. 
I built the new version using your steps on README. I will refer to it as the **github** version.
For both version, I simply called the binary. 
```
/usr/bin/wayvnc 0.0.0.0 5901
$HOME/tools/wayvnc/build/wayvnc 0.0.0.0 5902
```

### Versions

Server: Ubuntu 23.10 on Raspberry Pi 5

**apt** version:
```
$ /usr/bin/wayvnc -V
wayvnc: 0.6.0
neatvnc: 0.6.0
aml: 0.3.0
```

**github** version:
```
$ ./build/wayvnc -V
wayvnc: v0.9-dev-bd9daa8 (master)
neatvnc: v0.9-dev-d95b678 (master)
aml: v0.3.0-1-gede4249 (master)
```

Sway was installed via `apt`
```
$ sway -v
sway version 1.8.1
```

Client: TigerVNC `vncviewer64-1.13.1.exe` on Windows 11

### The Rabbit Hole

First of all, "Automatic server-side resizing of headless outputs" is not working. So I turned on `--log-level=trace`, after I resize the viewer window, I get this from trace:
```
TRACE: ../src/main.c: 251: Registering new xdg_output_manager
TRACE: ../src/main.c: 269: Registering new wlr_output_manager
TRACE: ../src/main.c: 261: Registering new wlr_output_power_manager
TRACE: ../src/main.c: 229: Registering new output 41
TRACE: ../src/output-management.c: 184: New head, now at 1
TRACE: ../src/output-management.c: 42: Got head name: HEADLESS-1
TRACE: ../src/output-management.c: 51: Got head description: Headless output 1
TRACE: ../src/output-management.c: 65: Got head mode
TRACE: ../src/output-management.c: 71: Got head enabled: no
TRACE: ../src/output-management.c: 162: Got new serial: 1
TRACE: ../src/output.c: 226: Output 41 name: HEADLESS-1, headless: yes
TRACE: ../src/output.c: 236: Output 41 description: Headless output 1
TRACE: ../src/output.c: 279: Output HEADLESS-1 power state changed to ON
Info: Capturing output HEADLESS-1
Info: >> Headless output 1 2560x1440+0x0 Power:ON
DEBUG: ../subprojects/neatvnc/src/server.c: 1908: Trying address: 0.0.0.0
DEBUG: ../subprojects/neatvnc/src/server.c: 1928: Successfully bound to address
Info: Listening for connections on 0.0.0.0:5901
DEBUG: ../src/ctl-server.c: 809: Initializing wayvncctl socket: /run/user/1000/wayvncctl
Info: New client connection from 192.168.50.201: 0xaaaaeb72b160 (ref 1)
DEBUG: ../subprojects/neatvnc/src/server.c: 799: Client chose security type: 1
Info: Starting screen capture
DEBUG: ../src/main.c: 1342: Client connected, new client count: 1
DEBUG: ../src/ctl-server.c: 941: Enqueueing client-connected event: {"id":"1","address":"192.168.50.201","username":null,"seat":"seat0","connection_count":1}
DEBUG: ../src/ctl-server.c: 968: Enqueued client-connected event for 0 clients
DEBUG: ../subprojects/neatvnc/src/server.c: 1048: Client 0xaaaaeb72b160 set encodings: cursor,desktop-size,extended-desktop-size,qemu-extended-key-event,tight,copyrect,open-h264,zrle,hextile,rre,copyrect,raw
Info: Choosing tight encoding for client 0xaaaaeb72b160
DEBUG: ../src/main.c: 804: Client resolution changed: 3840x2054, capturing output HEADLESS-1 which is headless: yes
TRACE: ../src/output-management.c: 258: disabling output HEADLESS-1
TRACE: ../src/output-management.c: 280: applying new output config
TRACE: ../src/output-management.c: 139: config request failed
```
Looks like it detects the change on client side but couldn't resize. 

So I did another experiment. 
1. I restarted sway. I can change the resolution by calling `swaymsg output HEADLESS-1 resolution 1280x720`. 
2. I started the apt version wayvnc. I can still change the resolution on the fly (on HEADLESS-1 with `foot`).
3. I restarted sway. 
4. I started the github version wayvnc. I can still change the resolution if no viewer has connected to the server.
5. But after a viewer is connected (and even after it's disconnected, or stop wayvnc server), `swaymsg output HEADLESS-1 resolution 1280x720` is not working.

sway is giving out this error:
```
sway[3150]: 00:04:48.881 [INFO] [sway/commands.c:260] Handling command 'output HEADLESS-1 resolution 1280x720'
sway[3150]: 00:04:48.881 [DEBUG] [sway/commands.c:432] Subcommand: resolution 1280x720
sway[3150]: 00:04:48.881 [DEBUG] [sway/config/output.c:217] Merging on top of existing output config
sway[3150]: 00:04:48.881 [DEBUG] [sway/config/output.c:240] Config stored for output HEADLESS-1 (enabled: 0) (1280x720@-1.000000Hz position -1,-1 scale 2.000000 subpixel unknown transform -1) (bg #000000 solid_color) (power -1) (max render time: -1)
sway[3150]: 00:04:48.881 [DEBUG] [sway/config/output.c:390] Turning off output HEADLESS-1
sway[3150]: 00:04:48.881 [DEBUG] [sway/config/output.c:506] Committing output HEADLESS-1
sway[3150]: 00:04:48.881 [DEBUG] [wlr] [backend/headless/output.c:37] Unsupported output state fields: 0x8
sway[3150]: 00:04:48.881 [ERROR] [sway/config/output.c:511] Failed to commit output HEADLESS-1
```

Furthermore, I tracked down the source for `sway`/`wlroots` regarding `Unsupported output state fields: 0x8`. Although I didn't have the time to build and test sway 1.9. But I believe this is fixed in wlroots 0.17.0 (ie. sway 1.9). Possibly in this merge request (https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4236).

### Next Step

Thanks for taking the time reviewing this and go down this rabbit hole with me. I actually wrote most of this before I found out the real issue. 
Although this may not be a bug, here are some suggestions:
- If we want backward compatibility, we should try to make this work for sway < 1.9 as well, since `swaymsg output` was usable before but not anymore.
- Or at least, it would be nice if there is a guide on how to set this up, or state that **sway 1.9 is required for wayvnc 0.8 to work properly**.

**Comment by any1** [comment]
Although it would be nice to have, a compatibility matrix is added work that I'm not willing to take on.
