### ISSUE TITLE
Wayland Protocol for Seat Management

### ISSUE THREAD

**Issue by any1** [any1/wayvnc#3]
Create a new protocol for managing input device seats from wayland clients. This allows us to create a new seat from wayvnc for it to use with virtual input devices.

There are some benefits to using separate seats:
 * Using `seat0` can mess with the user's selected keyboard layout.
 * If multiple users are using the system, they don't have to compete for the pointer. This can be useful when receiving remote tech support via VNC.
 * Users have their own sets of active keyboard modifiers (caps lock, shift, ctrl, etc.).

**Comment by ammen99** [comment]
Is this going to be optional? I.e will wayvnc work also for compositors which do not support this protocol?

**Comment by any1** [comment]
> Is this going to be optional? I.e will wayvnc work also for compositors which do not support this protocol?

This should be optional to begin with because many clients are either not multi-seat capable or buggy in that regard due to little testing having been made with multiple seats.

**Comment by bqv** [comment]
Does this need to be implemented before https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/61 can be merged?

**Comment by any1** [comment]
It is implemented already: https://github.com/any1/wayvnc/tree/transient-seats

**Comment by any1** [comment]
In fact, everything is implemented; just waiting for reviews and acks.
