### ISSUE TITLE
No input with WLR_BACKENDS=headless

### ISSUE THREAD

**Issue by mendelmaleh** [any1/wayvnc#30]
Is this expected behavior?
I get input with the same setup without that var, how do I launch it in headless with input? I tried `libinput,headless` but that freezed my tty till I killed it, `libinput,drm,headless` crashes with an error `failed to parse dbus propertieschanged`.

**Comment by any1** [comment]
But remote input via VNC works, right? If so, this is not a wayvnc issue.

**Comment by mendelmaleh** [comment]
Yeah it's not, however I thought people here would know the correct way to run sway with wayvnc.
For future reference, keyboard input worked with `WLR_BACKENDS=libinput,headless sway` and that will capture from whatever tty you ran that from too.
