### ISSUE TITLE
Missing mouse pointer on Pis < 4

### ISSUE THREAD

**Issue by lurch** [any1/wayvnc#307]
On Raspberry Pi devices earlier than a Raspberry Pi 4, when you try connecting to WayVNC there's no cursor in the VNC client window, and the mouse-cursor also disappears on the HDMI monitor attached to the Pi! When you close the VNC client, the mouse reappears on the Pi's HDMI monitor.
Note that by default Raspberry Pi devices earlier than a Raspberry Pi 4 will always run X11 (and not Wayfire), so this is probably why this bug hasn't been spotted before.

**Version:**
```
wayvnc: 0.8.0
neatvnc: 0.8.0
aml: 0.3.0
```

Describe how to **reproduce** the problem:
* Download / Flash [Raspberry Pi OS Bookworm](https://www.raspberrypi.com/software/) to an SD card
* Boot up the card in a Raspberry Pi (with an ethernet cable, USB mouse, USB keyboard and HDMI monitor connected to the Pi)
* Set username / hostname / locale / etc. (or do this in RPi Imager if you prefer)
* Make sure OS is fully up to date with: `sudo apt update && sudo apt full-upgrade`
* Edit `/usr/bin/xfallback.sh` to always `return 1` (this is needed to get Wayfire loading on **all** models of Pi
* Reboot (to ensure that all updates get applied)
* In `Preferences` -> `Raspberry Pi Configuration` -> `Interfaces` enable `VNC` and click OK
* Try connecting to the Pi using e.g. TigerVNC from another computer
  * On a Raspberry Pi 4 or Raspberry Pi 5 (using either 32-bit or 64-bit Bookworm), the mouse cursor works correctly in both the TigerVNC window and on the Pi's HDMI monitor, regardless of which mouse (computer or Pi) is used
  * On a Raspberry Pi 2  (using 32-bit Bookworm) or Raspberry Pi 3B+ (using either 32-bit or 64-bit Bookworm) as soon as TigerVNC connects, the mouse cursor disappears from the Pi's monitor, and there's no mouse cursor inside the TigerVNC window either. If you move either mouse to the very top-left of the window/screen then you can see the tooltip hover-text so there _is_ a (moving) mouse-cursor, it's just completely invisible! :ghost:  If you close the TigerVNC window on your computer and then jiggle the mouse connected to the Pi, the mouse-cursor reappears on the Pi's monitor.

**Comment by any1** [comment]
This looks more like a wayfire bug to me. What do you think @spl237?

**Comment by spl237** [comment]
@lurch - can you please test on labwc and see if the problem exists on there as well? If not, it's probably a wayfire issue.

**Comment by lurch** [comment]
Hmm, the plot thickens... On a Raspberry Pi 4 or Raspberry Pi 5, WayVNC works fine with both Wayfire and Labwc (both WayVNC 0.8.0 / 0.9-dev and 32-bit / 64-bit RPi OS).

On a Raspberry Pi 3B+, WayVNC works fine with Labwc. With WayVNC 0.8.0 and Wayfire I get the behaviour described above, where the desktop is visible on both the HDMI monitor and in the TigerVNC window, but the mouse-pointer is invisible in both (regardless of which mouse is moved). With WayVNC 0.9-dev (added to our public repo today) and Wayfire, when I connect with TigerVNC the mouse-pointer disappears on the HDMI monitor, and the TigerVNC window is completely black (yikes!). If I jiggle the mouse on my laptop (i.e. in TigerVNC) or the USB mouse attached to the Pi, then the mouse-cursor appears _very_ briefly on the HDMI monitor, but then disappears again. (same behaviour in both 32- and 64-bit RPi OS)

So definitely looks like a Wayfire bug (as Labwc always works fine), but seems curious that using wayfire gives different behaviour with WayVNC 0.8 and 0.9 ?

**Comment by lurch** [comment]
> Is the screen also blank if you tell TigerVNC to use tight encoding instead of auto selecting?

Yes.

**Comment by any1** [comment]
> > Is the screen also blank if you tell TigerVNC to use tight encoding instead of auto selecting?
> 
> Yes.

@spl237, You might want to check what happens if you try connecting via TigerVNC to a Pi 3 with the HDMI connected.

Anyway, the originally reported bug is most likely an issue with wlroots. Normally, wlroots based compositors will enforce software rendering of cursors when the output is being captured (if the capturing client requested the cursor to be rendered). Perhaps, something has gone wrong with that logic.

Please open a new issue for the "black" screen when you've found out more about it.
