### ISSUE TITLE
KDE support 

### ISSUE THREAD

**Issue by guyluz11** [any1/wayvnc#308]
It would be nice to have KDE support.

There are couple of reasons why that would benefit the project. 

1. KDE Plasma Mobile is a project to make KDE run on the phone, this technology could help it advance forward to being even more than Linux phone.
2. Steam deck (gaming console) runs KDE, could benefit users to connect it to the TV without cables.
3. KDE having a lot of market share so supporting it means more users who are using this tool and can advance it forward.

**Comment by any1** [comment]
KDE would need to support required protocol extensions. They have some of their own vendor specific extensions, which could be implemented in wayvnc, but this appears incomplete with regard to input.
