### ISSUE TITLE
How to setup WayVNC server ?

### ISSUE THREAD

**Issue by freebrowser1** [any1/wayvnc#316]
### Useful information:
Please, try to gather as much of useful information as possible and follow
these instructions:

- **Version:**
`wayvnc -V`
ayvnc: 0.4.1
neatvnc: 0.4.0
aml: 0.2.1
Ubuntu 22.04 LTS (arm64, running Wayland gnome)

- Describe how to **reproduce** the problem

Well, maybe dumb question.
I installed wayvnc by `sudo apt install wayvnc` from a terminal.
Then I did:
```

$ wayvnc 
wl_registry@2: error 0: invalid version for global wl_seat (15): have 5, wanted 7
ERROR: Virtual Pointer protocol not supported by compositor.
ERROR: Failed to initialise wayland
```
With sudo I get this:
```
$ sudo wayvnc 
[sudo] password for me:
wl_registry@2: error 0: invalid version for global wl_seat (15): have 5, wanted 7
ERROR: Virtual Pointer protocol not supported by compositor.
ERROR: Failed to initialise wayland
```

So probably a configuration file was lacking. Indeed I could not find any standard configuration file, neither under `/home/me/.config` (non-root) nor under `/etc/wayland` (root).
It also lacks documentation how to setup the server, unlike TightVNC, TigerVNC oe X11VNC. These three however don't support Wayland, hence I tried WayVNC.

So, how should I setup the server ?

**Comment by Consolatis** [comment]
What wayland compositor are you using? Based on the logs it seems to be missing some wayland protocols (or new versions of the protocol) that wayvnc requires.

**Comment by freebrowser1** [comment]
> Gnome is not supported. See the [readme](https://github.com/any1/wayvnc?tab=readme-ov-file#wayvnc).
Weird. Most Linux distros are shipped with Gnome.
