### ISSUE TITLE
ERROR: Unknown option: "show-performance"

### ISSUE THREAD

**Issue by net147** [any1/wayvnc#317]
- **Version:**
wayvnc: v0.8.0-15d09b0 (makepkg)
neatvnc: v0.8.0-46432ce (makepkg)
aml: v0.3.0-0-gb83f357 (makepkg)

- Describe how to **reproduce** the problem

"wayvnc --show-performance" (as mentioned in the manual) doesn't work and shows the following:
ERROR: Unknown option: "show-performance"

However, with "wayvnc --performance" wayvnc starts.

**Comment by any1** [comment]
Fixed. Thanks!
