### ISSUE TITLE
Wrong version prerequsite of neatvnc.

### ISSUE THREAD

**Issue by lyonlh** [any1/wayvnc#325]
The latest version of neatnvc is only 0.8.1 but meson.build requires `neatvnc_version = ['>=0.9', '<0.10.0']`.
https://github.com/any1/wayvnc/blob/7b8625855125c6816a8d558f0ad4617789c73989/meson.build#L60

**Comment by any1** [comment]
This is  not wrong. Neat VNC git master has version 0.9.
