### ISSUE TITLE
Wayvnc double free corruption

### ISSUE THREAD

**Issue by drigoskalwalker** [any1/wayvnc#334]
Hi, wayvnc works with defaults parameters but when I set authentication on config file I got this.

roott@darkstar:~# wayvnc -v
double free or corruption (fasttop)
Aborted

My config file:
use_relative_paths=true
address=0.0.0.0
#port=5900
enable_auth=true
username=root
passord=password

**Comment by any1** [comment]
Fixed. Thanks.

**Comment by drigoskalwalker** [comment]
My W key of my keyboard is falling
I typed passord in the config file not password
I fixed that and the server started normally.
