### ISSUE TITLE
Dead keys are not working (Acute, Grave, Circumflex)

### ISSUE THREAD

**Issue by josefwegner** [any1/wayvnc#356]
- **Version:**
wayvnc: 0.9-dev
neatvnc: 0.9-dev
aml: 0.3.0

- Describe how to **reproduce** the problem
Press a dead key from a client that does not eliminate dead keys and press the acute, grave or circumflex key followed by space.
wayvnc outputs:
```
ERROR: ../src/keyboard.c: 400: Failed to look up keyboard symbol: acute
ERROR: ../src/keyboard.c: 400: Failed to look up keyboard symbol: grave
ERROR: ../src/keyboard.c: 400: Failed to look up keyboard symbol: asciicircum
```

- What is supposed to happen:
Wayvnc should accept the input and print ', `, ^ and the accented letters like ê, é, è.

**Comment by any1** [comment]
Did you set a keyboard layout?

**Comment by josefwegner** [comment]
Yes, I did set at keyboard layout in ~/.config/wayvnc/config:
`xkb_layout=de`

**Comment by any1** [comment]
Which client are you using?

If I disable the qemu keyboard extension (so that I'm going through the same code path as you) and connect with Tiger VNC, it works fine both when setting `--keyboard=is` or `xkb_layout=is`.

If I don't set the keyboard layout, the error message I get is
```
ERROR: ../src/keyboard.c: 401: Failed to look up keyboard symbol: dead_acute
```

Maybe the client is sending the wrong symbol?

**Comment by josefwegner** [comment]
I am using TwinVNC (https://os4depot.net/?function=showfile&file=network/misc/twinvnc.lha) on Amiga OS 4.1 FE Update 2.

**Comment by any1** [comment]
Well, these symbols can often be typed on their own without being "dead" and I'd rather not take away that feature by converting them to dead keys, so this must be fixed in the client.

**Comment by josefwegner** [comment]
Sorry, I do not get what you are saying. How exactly does Wayvnc expect to receive the following characters?
- ^
- `
- '
- ê, â, î, û, ...
- é, á, í, ú, ...
- è, à, ì, ù, ...

**Comment by any1** [comment]
There is a difference between a "dead acute" and "acute". The client needs to send the "dead acute" symbol is the next character is to be something like "é". Your client is just sending "acute" where it should be sending "dead_acute".

**Comment by josefwegner** [comment]
Ah, that makes sense. The client also needs to send "dead acute" for the acute itself (Acute + space = `)?

**Comment by Consolatis** [comment]
`xkb_layout=de(nodeadkeys)` might allow you to send the keys by themselves.
