### ISSUE TITLE
Support for systemd sockets?

### ISSUE THREAD

**Issue by Ra2-IFV** [any1/wayvnc#357]
### Useful information:
Please, try to gather as much of useful information as possible and follow
these instructions:

- **Version:**
  - Run this command: `wayvnc -V`

0.8.0-2

- Try to reproduce while capturing a **trace log:**
  - `wayvnc -Ltrace | tee wayvnc-crash.log`

- Get the **stack trace**:
  - If have `coredumpctl`, you can gather the stack trace after a crash using
    `coredumpctl gdb wayvnc` and then run `bt full` to obtain the stack trace.
  - Otherwise, you can either locate the core file and load it into gdb or run
    wayvnc in gdb like so:
    - `gdb --args wayvnc -Ltrace`
  - If the lines mentioning wayvnc, neatvnc or aml have `??`, please compile
    wayvnc and those other projects from source with debug symbols and try
    again.

```
Info: Capturing output OUTPUT
Info: >> Headless output 11 1920x1080+0x0 Power:ON
Info: -- MONITOR 0000000000000 (HDMI-1) 1920x1080+0x0 Power:ON
ERROR: ../wayvnc/src/main.c: 893: Failed to bind to address. Add -Ldebug to the argument list for more info.
Process 100000 (wayvnc) of user 10000 dumped core.

Stack trace of thread 626156:
#0  0x000073d0600d4984 aml_ref (libaml.so.0 + 0x2984)
#1  0x000073d0600d53c8 aml_stop (libaml.so.0 + 0x33c8)
#2  0x00005ada052260ba n/a (wayvnc + 0xb0ba)
#3  0x00005ada05227a9b n/a (wayvnc + 0xca9b)
#4  0x00005ada0522083e n/a (wayvnc + 0x583e)
#5  0x000073d05fe42e08 n/a (libc.so.6 + 0x25e08)
#6  0x000073d05fe42ecc __libc_start_main (libc.so.6 + 0x25ecc)
#7  0x00005ada05221395 n/a (wayvnc + 0x6395)
ELF object binary architecture: x86-64
```

- Describe how to **reproduce** the problem

wayvnc.socket
```systemd
[Unit]
Description=WayVNC socket

[Socket]
ListenStream=0.0.0.0:5901

[Install]
WantedBy=sockets.target
```
wayvnc.service
```systemd
[Unit]
After=network.target

[Service]
Type=simple
Environment='WAYLAND_DISPLAY=wayland-0'
ExecStart=wayvnc -Ltrace --unix-socket
```
config
```conf
# address=0.0.0.0
# port=5901

enable_auth=false

use_relative_paths=true
```

**Comment by layercak3** [comment]
There is support via the external listener fd feature introduced in 0.9.0 (but not the specific sd_listen_fds(3) protocol). With your set of units you would use `ExecStart=wayvnc [...] -x 3` to treat the address argument (3) as an fd which is where systemd's socket would be accessible from. You should also have `Requires=wayvnc.socket` in the [Unit] section of wayvnc.service in case you ever start wayvnc.service manually without it being triggered by socket activation, otherwise wayvnc would start with fd 3 being unusable.

**Comment by Ra2-IFV** [comment]
My distro is still on 0.8.0 I'll report once I got the update.

**Comment by any1** [comment]
That looks like a separate issue. Please report this as a new issue and follow the instructions in the issue template.

**Comment by pipe01** [comment]
In case anyone comes across this, here's a copypasta:

`wayvnc.socket`:
```
[Unit]
Description=VNC server socket

[Socket]
ListenStream=0.0.0.0:5900

[Install]
WantedBy=sockets.target
```

`wayvnc.service`:
```
[Unit]
After=network.target

[Service]
Type=simple
ExecStart=wayvnc -x 3
```
