### ISSUE TITLE
wl_seat binding to wrong version

### ISSUE THREAD

**Issue by tim-win** [any1/wayvnc#36]
Despite having fedora 31 and wayland-devel 1.17.0, I consistently run into the wrong wl_seat getting bound:
```
wl_registry@2: error 0: invalid version for global wl_seat (16): have 5, wanted 7
ERROR: Virtual Pointer protocol not supported by compositor.
ERROR: Failed to initialise wayland
```
This happens both when compiling locally via the description in the readme, and when trying the wef/wayvnc copr described in another issue.

I double checked 1.17.0, the latest version available for fedora 31, and the version of wl_seat truly is 7: https://github.com/wayland-project/wayland/blob/1.17.0/protocol/wayland.xml#L1665

Not sure what is providing wl_seat 5, but as long as it is apparently available on my system wayvnc is failing.

**Comment by any1** [comment]
Maybe your compositor (sway or wayfire) is built with 5?

**Comment by tim-win** [comment]
Yep- my bad. Closing.
