### ISSUE TITLE
Trying to build causes general protection fault (CPU instruction usage?)

### ISSUE THREAD

**Issue by ilyazzz** [any1/wayvnc#37]
I'm trying to build the package with makepkg, the build itself hangs, and the whole system becomes half-unusable(only some programs launch, some running ones hang).
Dmesg shows a general protection fault. Full log: https://pastebin.com/raw/F4n3L9kj

I've also tried to use a package built on a different system, and it crashes with "illegal hardware instruction".

I'm running an i5 750 on Arch Linux with the 5.6.8-zen kernel. Perhaps wayvnc tries to use some instructions my CPU doesn't support (AVX)?

**Comment by any1** [comment]
See #34

**Comment by any1** [comment]
Never mind that last comment. What you have is a kernel panic which seems to have been somehow triggered by makepkg or meson. Is the zen kernel perhaps compiled with a SIMD extension? A userspace program with an illegal instruction should never affect the kernel in this way.

**Comment by ilyazzz** [comment]
I've tried building wayvnc manually from git, it builds and works properly. The `wayvnc-git` AUR package builds successfully, but it still crashes with "illegal hardware instruction" when running it. Seems like the PKGBUILDs are enabling AVX?

` zcat /proc/config.gz | grep SIMD` output, just in case:
`CONFIG_CRYPTO_SIMD=m`

Not sure if this should be closed as it's a packaging issue (and the non -git package predates the #34 fix)

**Comment by any1** [comment]
The `wayvnc-git` AUR is not maintained and is in fact older than the `wayvnc` AUR

**Comment by any1** [comment]
I set the default SIMD extension to sse2 now. I hope that's old enough for everyone. :)
