### ISSUE TITLE
very high latency

### ISSUE THREAD

**Issue by grandinj** [any1/wayvnc#39]
I'm seeing 750ms+ latency talking between 2 boxes on the same network (on the same switch).

Both powerful multi-core machines.

This is with Fedora32. 

Is the TCP connection perhaps running with Nagle active?

**Comment by any1** [comment]
You can try setting `TCP_NODELAY` here if you like: https://github.com/any1/neatvnc/blob/master/src/server.c#L720

**Comment by grandinj** [comment]
My apologies, this was logged against the wrong VNC project, this is a gnome-remote-desktop/pipewire issue
