### ISSUE TITLE
Cant start it - error Failed to initialize renderer

### ISSUE THREAD

**Issue by waligu** [any1/wayvnc#41]
I use Gentoo compiled nearly without any X protocol in it

After starting wayvnc those both messages came up 

DEBUG: OpenGL ES 3.2 Mesa 20.0.6
ERROR: Failed to initialise renderer

i don't get what is missing or what he trys to initialise. There is no log

**Comment by any1** [comment]
Can you run `glxinfo` from the `mesa-progs` package and post the results here?

**Comment by any1** [comment]
This might be a duplicate of #24.

**Comment by waligu** [comment]
[glx.txt](https://github.com/any1/wayvnc/files/4647733/glx.txt)

**Comment by waligu** [comment]
that are the results from the run

**Comment by any1** [comment]
This is no longer relevant as OpenGL is no longer used for rendering.
