### ISSUE TITLE
Modifier keys get 'stuck'.

### ISSUE THREAD

**Issue by dnfm** [any1/wayvnc#42]
This is probably related to issue #35, but now sometimes modifier keys get stuck.

In my experience, it appears to always be the floating modifier/$mod key (alt).

Sometimes, I can 'unstick' it by smashing all of the modifier keys in succession, sometimes, the only way to get it to unstick is to kill and restart wayvnc.

The output from wayvnc doesn't look any different when the modifier is stuck, it says

DEBUG: symbol=a level=0 code=AC01 pressed
DEBUG: symbol=a level=0 code=AC01 released

But it's passing ALT-A to the sway session.

**Comment by any1** [comment]
Which client are you using? Which clients have you tried? Does this happen on all of them?

**Comment by dnfm** [comment]
I've tried both the VNC official client as well as vinagre.  Yes it happens on both.

Although oddly, it seems to be easier to 'unstick' vinagre.  Though vinagre it also happens on more often. (Though I wonder if that has something to do with the fact that vinagre will actually pass *all* characters to wayvnc, whereas the official client lets the window manager/compositor steal input for its own shortcuts.)

**Comment by any1** [comment]
By official, do you mean Real VNC Viewer?

**Comment by dnfm** [comment]
I do.

**Comment by any1** [comment]
What version of sway & wlroots are you running? How long does it normally take you to trigger this?

I've been trying for a few minutes now with vinagre.

By the way, vinagre is awfully slow. I can actually see it progressively drawing frames. :)

**Comment by dnfm** [comment]
It was a lot easier to replicate with the realvnc client, and vinagre is a giant pile of crap, but it's the only linux vnc client I've found so far that properly intercepts keystrokes and sends them to the server rather than open terminals on the client system when I hit alt-enter. :)

Anyway, the version of sway and wlroots I'm using are current HEAD of master from git.

**Comment by dnfm** [comment]
I've found a really easy way to recreate this issue that works 100% of the time.

Press and hold ALT:
DEBUG: Symbol=Alt_L level=0 code=LALT pressed

Press and release the SHIFT key (while still holding ALT):
DEBUG: Symbol=Shift_L level=0 code=LFSH pressed

Now release the ALT key.  Nothing.  Alt is now stuck on.
(Releasing the Shift key still does the right thing.)

If you press ALT again, you get nothing except the 'release' message when it happens.

If you press alt, then press shift, release shift, then release alt, all is well.
If you press alt, then press shift, then release alt, then release shift, alt is now stuck.

I've been able to confirm this with every VNC client I've tested.

**Comment by any1** [comment]
I can also reproduce this. Thanks!

I pushed a change that fixes it. Can you try it out?

**Comment by dnfm** [comment]
My initial testing seems to confirm it works.  My workflow involves a lot of ALT-shift-keys so if there are any other issues, I'm sure I'll know pretty quickly.

I think this one is fixed for now, though.

Thank you again.  wayvnc is fantastic.

**Comment by any1** [comment]
Very good.
