### ISSUE TITLE
wayvnc pegs the CPU if its output goes away.

### ISSUE THREAD

**Issue by dnfm** [any1/wayvnc#43]
If wayvnc is started with -o <output> and then that input is taken away (in my case, from unplugging an hdmi cable from my laptop), the wayvnc process went to 168% CPU usage on my laptop, and all the negative things that go along with that.

**Comment by any1** [comment]
Oh, yeah, I haven't implemented a handler for this.

**Comment by any1** [comment]
Fixed by https://github.com/any1/wayvnc/commit/4f1bca55c3bf19a58e9d892a5141fdfc5159bf01

**Comment by dnfm** [comment]
Works as expected.  Thanks!
