### ISSUE TITLE
wayvnc shows sway's cursor even without --render-cursor specified

### ISSUE THREAD

**Issue by colemickens** [any1/wayvnc#47]
Maybe I'm misunderstanding, and I am making some guesses here.

I upgraded my VNC client and noticed that I stopped getting my client-side cursor. It appears TightVNC made a change so as to not show the Windows cursor if the server is renderign the cursor. However, this is now the case no matter what options I pass to `wayvnc`.

So for now, I'm using the older client, where I get both cursors. For some reason, the immediately responsive cursor makes the entire system feel more responsive. Is this possibly a protocol bug in wayvnc? (aka/or a bug in the `-r` flag?)

**Comment by colemickens** [comment]
For anyone who might read this, on Windows, I just tried TurboVNC, it can capture keyboard, easily go in/out of fullscreen, has good out of box perf compared to TightVNC and UltraVNC, and can override the cursor to always render.

**Comment by any1** [comment]
This happens when sway uses software cursors, I think, which is always the case for headless. Maybe you can turn off sway's cursor as a workaround?

**Comment by any1** [comment]
Client side cursor rendering is planned, but not implemented: https://github.com/any1/neatvnc/issues/20

Currently wayvnc can't know which cursor the compositor wants to display, but maybe we can add a protocol for it.
