### ISSUE TITLE
WayVNC uses an obscene amount of CPU.

### ISSUE THREAD

**Issue by dnfm** [any1/wayvnc#51]
I believe this may be the result of a recent commit, as I've been using WayVNC for some time, and a recent git pull and reinstall has my laptop CPU fan going nuts.

I have two copies of wayvnc running.  One for each output.  One is 1920x1080 and the other is 2560x1440.  Just moving the mouse around in a window has WayVNC using > 100% of one CPU on an i7-8650U.

Enough mouse movement, and the mouse will actually start getting choppy in the window.

**Comment by any1** [comment]
Are you on master? How are things if you revert back to this commit? https://github.com/any1/wayvnc/commit/0a139a1ac469dfaecafe49c02f5e603a91d9acce

**Comment by dnfm** [comment]
I am on master.

I tried reverting that commit, but then wayvnc won't build because of too many arguments to aml_new.

I tried backing out the commit that changed that in aml, but too much has changed since then, and it crashed and burned horribly.

**Comment by dnfm** [comment]
No difference.

**Comment by any1** [comment]
Hah!

Which arguments do you pass to wayvnc and which version of wlroots do you have?

**Comment by any1** [comment]
Did checking out at that commit also fix your swaylock issue?

**Comment by any1** [comment]
Also, it would be really helpful if you could run a profiler such as `perf` to see where that CPU load comes from. I was not able to reproduce this yesterday. I even tried it on my tp x220 and it worked just fine.

**Comment by dnfm** [comment]
Yes it did fix the swaylock issue.

If I get some time later today, I'll see about profiling wayvnc.  Checking out to the commit you mentioned made it stop eating CPU badly enough to turn on the fan, but even this commit uses far more than a vnc server probably should (~30% CPU).

**Comment by any1** [comment]
Well, actually, VNC is inevitably quite heavy on the CPU. A very significant part of the work I've put into wayvnc has been to reduce CPU load.

**Comment by any1** [comment]
How is the CPU load on master now?

**Comment by dnfm** [comment]
I just gave it a try, and it seems to at least not cause my laptop to lag and start up its fan anymore, so better?  The CPU usage is still quite high, but I don't know what constitutes acceptable vs not acceptable.  Typing this right now into a wayvnc session has the wayvnc server on this output using about 30% of the CPU.

**Comment by any1** [comment]
That is quite high. Is that the baseline or does there need to be motion on the screen?

**Comment by dnfm** [comment]
The only 'motion' on the screen was the text being typed.

**Comment by any1** [comment]
I added back some frame counters. They can be enabled using the `-p` argument. If nothing is happening on the output, the counter should say that 0 frames were captured, is that the case?

**Comment by dnfm** [comment]
Yep.  And the damage check percentage seems mostly sane.

**Comment by any1** [comment]
Ok, I'll call this solved for now, then. There really isn't much that can be done apart from reducing the maximum frame rate. I recently increased it from 20 to 30, which might explain something.

I want to implement h264 hw encoding which will pass frames as DMA-BUFs straight from the compositor to vaapi. This should be much nicer on the CPU. Until then, the CPU will just have to do the work.

**Comment by dnfm** [comment]
Seems reasonable to me.  Thanks again.
