### ISSUE TITLE
Recent commit prevents wayvnc from working when swaylock is enabled.

### ISSUE THREAD

**Issue by dnfm** [any1/wayvnc#52]
Previously, I could unlock my sway instance remotely using wayvnc... now any attempt to send input to the wayvnc server when swaylock is enabled results in the server dying due to assert(!self->front).

So perhaps commit a6e1ba25?

**Comment by any1** [comment]
Is this still an issue?

**Comment by dnfm** [comment]
The latest master no longer has this issue.

**Comment by any1** [comment]
Ok, thanks for reporting and testing!
