### ISSUE TITLE
Add neatvnc and others as git submodule for easier building

### ISSUE THREAD

**Issue by ell1e** [any1/wayvnc#60]
These build instructions left me slightly confused, since there appears to be no subprojects directory and I wasn't entirely sure about how the layout is supposed to look like:
```

The easiest way to satisfy the neatvnc and aml dependencies is to link to them
in the subprojects directory:

git clone https://github.com/any1/wayvnc.git
git clone https://github.com/any1/neatvnc.git
git clone https://github.com/any1/aml.git

mkdir wayvnc/subprojects
cd wayvnc/subprojects
ln -s ../../neatvnc .
ln -s ../../aml .
cd -

```
And it made me wonder, why aren't these subprojects already present as git submodules such that a simple `git submodule init --update` would do the job? Seems like that'd be the more standardized, less surprising version that most are already familiar with

**Comment by any1** [comment]
I just think that git submodules are more trouble than they're worth. Maybe I just don't know how to use them, but the last time I tried to use them I ended up undoing the change because they were getting in the way of my work.
