### ISSUE TITLE
Pointer broken on multi-monitor systems where one or more monitors use scaling

### ISSUE THREAD

**Issue by kode54** [any1/wayvnc#64]
This is a redux of a previous issue, only this time, one or more of the outputs use scaling. In this case, I have a 3840x2160 primary monitor that is using 2.0 scaling so it has an effective resolution of 1920x1080, but visible resolution that is double that. The secondary monitor is 1920x1080 with a 1.0 scale.

The result of this scale and arrangement of outputs, is that the cursor seems to move vertically properly, but horizontally, it appears to span both monitors while it is moving across the one output in the VNC client. When the VNC client is on the secondary output, the cursor appears to only work on the visible output when it is on the right half of the VNC client, otherwise it clicks on the primary output.

**Comment by any1** [comment]
I am unable to reproduce this with headless displays. Which versions do you have of wayvnc and wlroots?

**Comment by kode54** [comment]
wlroots-git - 0.11.0.r44.gbae8d759-1
wayvnc-git - 0.2.0+8.g8038e65597-1

And specifically, I have one 3840x2160 display, scale 2.0, and 1920x1080 display, scale 1.0.

**Comment by kode54** [comment]
Yes, this may have to do with running with RealVNC's "official" iOS app. I now have another bug to report with VNC Viewer and wayvnc.

**Comment by kode54** [comment]
Do I need to enable full mouse coordinate logging to track this down?

**Comment by kode54** [comment]
This is still an issue with VNC Viewer. I don't know any other VNC client to try.

**Comment by kode54** [comment]
I figured it out. The absolute pointer api isn't constrained to a given output. The absolute cursor space encompasses the entire seat, with no handle to specify a single output.

**Comment by kode54** [comment]
Ah, different than I thought. wlroots supports that, but Wayfire is ignoring it in their implementation. I will report it there.

**Comment by kode54** [comment]
So this isn't technically your issue, I can close this one.
