### ISSUE TITLE
RealVNC iOS client "VNC Viewer" sends shifted keys that are received unshifted

### ISSUE THREAD

**Issue by kode54** [any1/wayvnc#70]
When using VNC Viewer on an iPad, the following log is generated as I connect and type a 3, a #, a 3, and another #:

```
DEBUG: Set nvnc buffer: 0x560a160eb5a0
ERROR: data_control_to_clipboard called with 0 length
DEBUG: symbol=3 level=0 code=AE03 pressed
DEBUG: symbol=3 level=0 code=AE03 released
DEBUG: Failed to match level on symbol: numbersign
DEBUG: symbol=numbersign level=1 code=AE03 pressed
DEBUG: Failed to match level on symbol: numbersign
DEBUG: symbol=numbersign level=1 code=AE03 released
DEBUG: symbol=3 level=0 code=AE03 pressed
DEBUG: symbol=3 level=0 code=AE03 released
DEBUG: Failed to match level on symbol: numbersign
DEBUG: symbol=numbersign level=1 code=AE03 pressed
DEBUG: Failed to match level on symbol: numbersign
DEBUG: symbol=numbersign level=1 code=AE03 released
```

All four end up typing a string of "3333".

**Comment by any1** [comment]
I don't see any shift key events in between. According to spec:

> The "shift state" (i.e. whether either of the Shift keysyms are down) should only be used as a hint when interpreting a keysym. For example, on a US keyboard the '#' character is shifted, but on a UK keyboard it is not. A server with a US keyboard receiving a '#' character from a client with a UK keyboard will not have been sent any shift presses. In this case, it is likely that the server will internally need to "fake" a shift press on its local system, in order to get a '#' character and not, for example, a '3'.

So, apparently we need to fake shift-key presses.

Anyhow, you wouldn't happen to be using a UK layout on the iPad?

**Comment by kode54** [comment]
US layout. And it does send shift keypresses, when using the modifier key toolbar. But not when using shift on the iOS onscreen keyboard. Although, VNC Viewer does attach a modifier key toolbar to the onscreen keyboard, and that *does* send shift keypresses. And is, in fact, the only way to send a # when pressing # with the onscreen keyboard. Or sending a : to vim.

**Comment by any1** [comment]
I'm experimenting with a different approach to keyboard handling that should fix this: https://github.com/any1/wayvnc/tree/stateless-keyboard

Care to try it out?

**Comment by Flakebi** [comment]
Slightly unrelated to the original issue here, I tried out the stateless-keyboard branch. It fixes the last issue I mentioned in #71 (nice!) but it breaks some modifiers, e.g. I cannot open a Terminal any more in sway by pressing Alt+Enter or Windows(/Mod4)+Enter, they are just registered as the key without the modifier. The debug log shows the modifier keys correctly though.

**Comment by any1** [comment]
Wayvnc (master) will now fake shift levels when it can't find an exact match at the current shift level.

**Comment by any1** [comment]
I've had reports from people on IRC that their shifting issues have been resolved and I've not received a reply on this issue yet, so I shall assume that it is indeed resolved. Please reopen if it turns out not to be resolved.

**Comment by kode54** [comment]
Yes, this does appear to be resolved now.
