### ISSUE TITLE
Screen jumping/artifacting.

### ISSUE THREAD

**Issue by dnfm** [any1/wayvnc#74]
This may be specific to something about my weird set up, and may (probably is?) a bug in wlroots/sway, but it only happens in wayvnc, so I thought I'd start here.

I run wayvnc on an external monitor hooked up to my laptop (as well as the laptop screen itself, but it doesn't exhibit this issue).  The laptop screen is 2560x1440 at position 0,1920.  The monitor is 1920x1080 @ 0,0 transformed 90 degrees.  I run two instances of wayvnc.  One for the laptop screen, and one for the external hdmi connection to the monitor.

My desktop has 5 physical outputs, and then 3 headless outputs.

The 3 headless outputs are VNCed to the two above mentioned outputs on my laptop, and then a windows vnc server on to the right of them.

headless-1 is at position 3840,1000 @ 1080x1920 running a vnc client to the transformed monitor on the laptop.
headless-2 is at position 3840,2920 @ 2560x1440 running a vnc client to the laptop built-in screen.

Every now and again, for no discernible reason, the video on the transformed 1920 screen hooked up to the laptop will start artifacting.  The screen will jump around, tear, and go crazy.

The fix?  Move the mouse back to the non headless outputs, just move the mouse off of that screen.  it only happens when that output has focus, only on that output, and randomly.

If I use the physical keyboard/mouse on the laptop and don't use wayvnc, it never happens.

If I kill wayvnc, it stops immediately.

I'm running latest trunk from git for wlroots, sway, and wayvnc (including aml/neatvnc).  wayvnc doesn't output anything strange.  I run wayvnc as: wayvnc -f 1 -o DP-2 -p 192.168.1.x 5433

**Comment by lack** [comment]
This is a very intriguing case, though I know it's been a while.

1. Does this still happen, or has something fixed this in the intervening years?

2. If it's still happening, am I right in my understanding that it only happens to a rotated screen? If so, could you temporarily alter your setup so it's not rotated, to see if that removes the issue?

**Comment by dnfm** [comment]
Yes it still does it.  It happens less often, but it does it.  I can fix it by literally putting my mouse in the window that's doing it.

I suspect it's a wlroots/sway issue, though.

I don't recall if it does it in non-rotated screens .. I think it does it in both, but I'm not 100% at this point.  It happens *VERY* infrequently these days, so all I can do is try to keep an eye out for it next time it happens.

**Comment by any1** [comment]
I'll close this for now. Please reopen if you can provide info on how to reliably reproduce the issue.
