### ISSUE TITLE
Constant "Basic output test failed" errors from Sway if WayVNC is running when SDL2 program is started

### ISSUE THREAD

**Issue by eero-t** [any1/wayvnc#77]
I'm not sure what's the correct place for this (wlroots, sway or wayvnc), so I filed it under what triggers the issue.

**Setup**

Fedora 33 package versions:
* sway v1.5
* wlroots v0.11.0
* wayvnc v0.3.0

**Problem**

Use-case:
* Start: `sway`
* Start: WAYLAND_DISPLAY=wayland-1 `wayvnc`
* Start: WAYLAND_DISPLAY=wayland-1 <SDL2 program>

Expected results:
* No errors as they don't happen when wayvnc isn't running
* Any error output is rate-limited to something sane

Actual result:
* VNC client output of Sway screen and the SDL2 application looks fine, so error doesn't seem very serious
* Following from Sway approximately at rate given by WayVNC "--max-fps" option:
```
00:00:03.677 [types/wlr_output.c:567] Basic output test failed
00:00:03.694 [types/wlr_output.c:567] Basic output test failed
00:00:03.711 [types/wlr_output.c:567] Basic output test failed
00:00:03.727 [types/wlr_output.c:567] Basic output test failed
```

PS. This looks similar to an earlier wlroots issue, but that was fixed clearly before wlroots v0.11.0 release, so I assume Fedora version to contain that fix:  https://github.com/swaywm/wlroots/issues/2164

I tried one another SDL2 program with this, but that didn't trigger the issue, so I assume problem to be one of the SDL options used by this program:
```
window = SDL_CreateWindow(name, x, y, w, h, SDL_WINDOW_FULLSCREEN|SDL_WINDOW_INPUT_FOCUS|SDL_WINDOW_ALWAYS_ON_TOP);
renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_PRESENTVSYNC|SDL_RENDERER_ACCELERATED);
SDL_CreateTexture(renderer, SDL_PIXELFORMAT_NV12, SDL_TEXTUREACCESS_STREAMING, w, h);
```
And such textures being blit to the screen.  Using 16-bit SDL_PIXELFORMAT_UYVY instead of the 12-bit one doesn't help.

(Program is for viewing video streams, that's why it's using video related formats, and unfortunately it's closed one.)

**Comment by any1** [comment]
Thanks for reporting but this is a wlroots issue.

**Comment by eero-t** [comment]
Ok, filed: https://github.com/swaywm/wlroots/issues/2532
