### ISSUE TITLE
Pointer broken on multi-monitor systems

### ISSUE THREAD

**Issue by artizirk** [any1/wayvnc#8]
Is it possible to capture all available outputs?

**Comment by any1** [comment]
No, this is currently not a feature, but you may be able to run a wayvnc session per output. I haven't tested this myself, but I suspect you may run into issues with the mouse. If you decide to try it, please tell us how it goes.

**Comment by artizirk** [comment]
I can can run the server for each screen but mouse input is stretched over both of the outputs

**Comment by any1** [comment]
Thank you. I've a feeling that this will be easily fixed.

**Comment by any1** [comment]
I believe this should be fixed now, but I don't currently have an extra display to test with. Can you confirm?

**Comment by artizirk** [comment]
Unfortunately with latest master the mouse input coordinates are still stretched across both screens

**Comment by artizirk** [comment]
So, I did some simple printf debuging.
I have two 2560x1440 screens side by side. 
`zwlr_virtual_pointer_v1_motion_absolute` in `pointer.c` is called with sensible values that are correctly less than 2560x1440 cordinates. So it is possible that sway it self is scaling the values it receives.

**Comment by any1** [comment]
It seems that I need to find out the width & height of the combined layout to be able to use the absolute motion with more than 1 display. I'm looking into that now.

**Comment by any1** [comment]
Hopefully this is the fix that we need:
https://github.com/swaywm/sway/pull/4979
https://github.com/swaywm/wlroots/pull/2019
https://github.com/swaywm/wlr-protocols/pull/71
https://github.com/any1/wayvnc/tree/input-output-mapping

**Comment by any1** [comment]
Fixed in master. Also requires wlroots master.

**Comment by kode54** [comment]
Doesn't seem to work correctly when one of the two outputs is using scaling.

**Comment by any1** [comment]
> Doesn't seem to work correctly when one of the two outputs is using scaling.

Please create a new issue
