### ISSUE TITLE
Mouse coordinates with mixed dpi multi monitor setup seem to span both outputs

### ISSUE THREAD

**Issue by kode54** [any1/wayvnc#82]
Return of #8 only it seems unaffected by the fix that went into that.

I am running wlroots from master, and wayvnc and its dependencies from master as well. Two monitors, one 3840x2160 at 0,0 scaled 2.0, so it has an effective resolution of 1920x1080, and a 1920x1080 display at 1920,0 scaled 1.0.

I can isolate the outputs using -o and the output name, either DP-1 or DP-2, but the cursor will respond as if the width of the VNC Viewer spans both displays. The height and y coordinate are handled correctly, though.

**Comment by any1** [comment]
Is this not the same as #64?

**Comment by kode54** [comment]
Leave it to me to not even notice my own issue, because I didn't use the appropriate keywords in the issue name. Closing this redundant issue.

**Comment by any1** [comment]
No problem. :)
