### ISSUE TITLE
Using without connected Screen - Headless

### ISSUE THREAD

**Issue by comcloudway** [any1/wayvnc#83]
Not experienced with Wayland in general, but from reading through some documentation, other related issues for wayvnc and some searching, it seems like I should be able to run wayvnc without any connected screen:
`export XDG_RUNTIME_DIR=~/.cache/xdgr`
`export WLR_BACKENDS=headless`
`export WLR_LIBINPUT_NO_DEVICES=1`
`./build/wayvnc`
Returns _**ERROR: Failed to initialize wayland**_
I tried using yay to install wayvnc, I tried building it from source even with the  --buildtype=debug meson flag, but the output stays the same. All runtime dependencies are satisfied, tried with and without the optional ones.
Running on aarch64 Manjaro arm in a chroot (I know aarch64 is not officially supported, but people mentioned it working in the aur comments)

uname -a:
`Linux localhost 4.14.117-perf+ #1 SMP PREEMPT Thu Sep 17 23:56:28 CDT 2020 aarch64 GNU/Linux`
My parent system is running Linux 4.17 thus the 4.17 kernel in the uname output, but manjaro itself is set up to use 5.10

If the problem is chroot related and there is no workaround, you may as well mark this issue as closed immediately

**Comment by any1** [comment]
You need to run inside a wayland session or set "WAYLAND_DISPLAY=wayland-1" (depending on what your wayland session is named)

Please ask questions in GitHub Discussions or IRC.

**Comment by comcloudway** [comment]
My Bad, coming from xorg Iexpected the vnc server to be starting the session
